---

dm_root: /srv/debmirror
dm_gpg_dir: "{{dm_root}}/gpg"
dm_mirrors_dir: "{{dm_root}}/mirrors"
dm_scripts_dir: "{{dm_root}}/scripts"
dm_log_dir: "{{dm_root}}/log"
dm_gpg_keyring: "{{dm_gpg_dir}}/trustedkeys.gpg"
dm_keyserver: keyserver.ubuntu.com
ubuntu_default_keyring: /usr/share/keyrings/ubuntu-archive-keyring.gpg
ws_mirrors_link: /var/www/html/mirrors

debmirrors:
  - name: ubuntu-16.04
    mirror: us.archive.ubuntu.com
    proto: http
    gpgkeys: "C0B21F32"
    arch: amd64
    sections: "main,restricted,universe,multiverse,main/debian-installer,restricted/debian-installer,universe/debian-installer,multiverse/debian-installer"
    releases: "xenial,xenial-security,xenial-updates,xenial-backports"
    src_path: /ubuntu
    dst_path: /ubuntu
    source: False
    nocleanup: True

  - name: ubuntu-20.04
    mirror: us.archive.ubuntu.com
    proto: http
    gpgkeys: "C0B21F32"
    arch: amd64
    sections: "main,restricted,universe,multiverse,main/debian-installer,restricted/debian-installer,universe/debian-installer,multiverse/debian-installer"
    releases: "focal,focal-security,focal-updates,focal-backports"
    src_path: /ubuntu
    dst_path: /ubuntu
    source: False
    nocleanup: True

  - name: ubuntu-24.04
    mirror: us.archive.ubuntu.com
    proto: http
    gpgkeys: "871920D1991BC93C"
    arch: amd64
    sections: "main,restricted,universe,multiverse,main/debian-installer,restricted/debian-installer,universe/debian-installer,multiverse/debian-installer"
    releases: "noble,noble-security,noble-updates,noble-backports"
    src_path: /ubuntu
    dst_path: /ubuntu
    source: False
    nocleanup: True
