---

  - name: install e2guardian pkgs
    apt:
      name: e2guardian
      state: latest
      install_recommends: yes
      update_cache: yes

  - name: deploy e2guardian.conf
    template:
      src: e2guardian.j2
      dest: /etc/e2guardian/e2guardian.conf
      owner: e2guardian
      group: e2guardian
      mode: 0640
    notify:
      - restart e2g

  - name: deploy ipgroups
    template:
      src: ipgroups.j2
      dest: "/etc/e2guardian/lists/authplugins/ipgroups"
      owner: e2guardian
      group: e2guardian
      mode: 0640
    notify:
      - restart e2g

  - name: generate all e2guardianfX.conf
    template:
      src: e2guardianfx.j2
      dest: /etc/e2guardian/e2guardianf{{item.num}}.conf
      owner: e2guardian
      group: e2guardian
      mode: 0640
    with_items: "{{filtering_groups}}"
    notify:
      - restart e2g


  - name: deploy e2g global cttb lists
    copy:
      src: cttb-lists/
      dest: /etc/e2guardian/lists/cttb
      owner: e2guardian
      group: e2guardian
      directory_mode: '0750'
      mode: 0640
    tags:
      - e2g_overrides
    notify:
      - restart e2g

  - name: create e2g filtering group dirs
    file:
      path: "/etc/e2guardian/f{{item.num}}"
      state: directory
      owner: e2guardian
      group: e2guardian
      mode: 0750
    with_items: "{{filtering_groups}}"
    tags:
      - e2g_overrides

  - name: create e2g filtering group default lists dirs
    file:
      path: "/etc/e2guardian/f{{item.num}}/defaults"
      state: directory
      owner: e2guardian
      group: e2guardian
      mode: 0750
    with_items: "{{filtering_groups}}"
    tags:
      - e2g_overrides

  - name: create e2g filtering group override dirs
    file:
      path: /etc/e2guardian/f{{item.num}}/overrides
      state: directory
      owner: e2guardian
      group: e2guardian
      mode: 0750
    with_items: "{{filtering_groups}}"
    tags:
      - e2g_overrides

  - name: deploy e2g filtering group override lists
    copy:
      src: "overrides/{{item.name}}/"
      dest: /etc/e2guardian/f{{item.num}}/overrides
      owner: e2guardian
      group: e2guardian
      mode: 0750
    with_items: "{{filtering_groups}}"
    tags:
      - e2g_overrides
    notify:
      - restart e2g

  - name: create e2g filtering group lists
    template:
      src: filtering-group-list-default.j2
      dest: "/etc/e2guardian/f{{item[0].num}}/defaults/{{item[1]}}"
      owner: e2guardian
      group: e2guardian
      mode: 0640
    with_nested:
      - "{{filtering_groups}}"
      - "{{filtering_groups_lists}}"
    tags:
      - e2g_overrides
    notify:
      - restart e2g

  - name: deploy custom.html access denied page
    template:
      src: access-denied.j2
      dest: /usr/share/e2guardian/languages/ukenglish/custom.html
      owner: root
      group: root
      mode: 0644
    notify:
      - restart e2g

  - name: deploy custom-bypass.html access denied page
    template:
      src: access-denied-bypass.j2
      dest: /usr/share/e2guardian/languages/ukenglish/custom-bypass.html
      owner: root
      group: root
      mode: 0644
    notify:
      - restart e2g

  - name: deploying blacklist files
    unarchive:
      remote_src: yes
      src: "{{ansible_assets_url}}/e2g-blacklist.tar.gz"
      dest: /etc/e2guardian/lists/
      owner: e2guardian
      group: e2guardian
