---

# lightdm configuration
lightdm_hide_users: false
lightdm_autologin_user: ""
lightdm_autologin_timeout: 0

# sw install
wpsoffice: false
libreoffice: true
openoffice: false
firefox: true
chrome: true
dropbox: false
skype: false

# look and feel
desktop_shortcuts: false
desktop_theme: Clearlooks
icon_theme: windos10-icons
pic_avatar: avatar-cttb.png
pic_bg: bg-windos10.jpg
start_icon: windos10-icons/scalable/places/start-here-symbolic.svg

# hardware
dell_aio: true
