---

  - name: install zfs
    apt:
      name: zfsutils-linux
      state: present

  - block:
    - name: create zpools
      command: "zpool create -f -o '{{item.pool_options}}' -O '{{item.dataset_global_options}}' {{item.name}} {{item.level}} {{item.disks|join(' ')}}"
      with_items: "{{zfs_pools}}"
      tags:
        zfs_pool

    - name: add slog to zpool
      command: "zpool add -f {{item.name}} log {{item.slog}}"
      with_items: '{{zfs_pools|selectattr("slog", "defined")|list}}'
      tags:
        zfs_slog

    - name: create datasets
      zfs:
        name: "{{item[0].name}}/{{item[1].name}}"
        state: present
        mountpoint: "{{item[1].mountpoint|default(omit)}}"
      with_subelements:
        - "{{zfs_pools}}"
        - datasets
      ignore_errors: yes
      tags:
        zfs_ds

    - name: create zvol
      zfs:
        name: "{{item[0].name}}/{{item[1].name}}"
        state: present
        volsize: "{{item[1].size}}" 
      with_subelements:
        - "{{zfs_pools}}"
        - zvols
      ignore_errors: yes
      tags:
        zfs_vol

    - name: set quota
      command: "zfs set quota={{item[1].quota|default('none')}} {{item[0].name}}/{{item[1].name}}"
      with_subelements:
        - "{{zfs_pools}}"
        - datasets
      tags:
        zfs_ds_quota

    - include: backups.yml
      when: zfs_backup is defined
      tags:
        - zfs_backup

    when: zfs_pools is defined
