---
# Ubuntu 22.04 / 24.04 specific desktop tasks

  - name: install ubuntu desktop minimal
    apt:
      state: present
      install_recommends: no
      name:
      - ubuntu-desktop-minimal
    tags:
      - packages
      - lubuntu

  - name: install WhiteSur GTK theme
    unarchive:
      remote_src: yes
      src: "{{ansible_assets_url}}/WhiteSur-gtk-theme.tar.gz"
      dest: /usr/share/themes/
      creates: /usr/share/themes/WhiteSur
      owner: root
      group: root
    tags:
      - sudhanix-core

  - name: install WhiteSur icon theme
    unarchive:
      remote_src: yes
      src: "{{ansible_assets_url}}/WhiteSur-icon-theme.tar.gz"
      dest: /usr/share/icons/
      creates: /usr/share/icons/WhiteSur
      owner: root
      group: root
    tags:
      - sudhanix-core

  - name: install WhiteSur cursor theme
    unarchive:
      remote_src: yes
      src: "{{ansible_assets_url}}/WhiteSur-cursors.tar.gz"
      dest: /usr/share/icons/
      creates: /usr/share/icons/WhiteSur-cursors
      owner: root
      group: root
    tags:
      - sudhanix-core
