; catchall incorrect extensions and play a message that they don't exist
; otherwise they just get a tone and it's puzzling to the least

; this cannot implemented with i in the cttb context as SIP will return a 404
; and never call i. instead use a catch-all context to be included at the end

[bogons] 
; doing _. catches everything which has side effects. Sticking to stricter patterns
exten => _XXXX,1,Answer()
 same => n,Wait(.5) 
 same => n,Sayalpha(${EXTEN}) 
 same => n,Playback(invalid) 
 same => n,Hangup()
