; CTTB Phone System
; Admin: spike@drba.org

; used to control outgoing calls from dvgs. All numbers are ultimately
; stored in cttb.conf since they are common to the City and need to talk
; to each other

[from-internal-dvgs]

include => from-internal-igdvs

include => from-internal-cttb
