; used for outgoing calls common to all igvds

[from-internal-igdvs]

;exten => _XXXXXXXXXX,1,Dial(Motif/google/${EXTEN}@voice.google.com,,r)
; only these numbers are allowed
exten => 7074620939,1,Dial(Motif/google/${EXTEN}@voice.google.com,,r) ;Administration Office
exten => 7073911805,1,Dial(Motif/google/${EXTEN}@voice.google.com,,r) ;Allen Huang
exten => 7074728714,1,Dial(Motif/google/${EXTEN}@voice.google.com,,r) ;Bill Palmer
exten => 6123608547,1,Dial(Motif/google/${EXTEN}@voice.google.com,,r) ;Daniel Phung
exten => 7073915029,1,Dial(Motif/google/${EXTEN}@voice.google.com,,r) ;Dennis Truong
exten => 7074683896,1,Dial(Motif/google/${EXTEN}@voice.google.com,,r) ;Girls Elementary
exten => 7074683847,1,Dial(Motif/google/${EXTEN}@voice.google.com,,r) ;Girls Highschool
exten => 7072280786,1,Dial(Motif/google/${EXTEN}@voice.google.com,,r) ;Indra Utpala
exten => 7072344726,1,Dial(Motif/google/${EXTEN}@voice.google.com,,r) ;Janice Jensen
exten => 7073915014,1,Dial(Motif/google/${EXTEN}@voice.google.com,,r) ;Jingong Shi
exten => 7074625486,1,Dial(Motif/google/${EXTEN}@voice.google.com,,r) ;Jintyan Shi
exten => 7073915016,1,Dial(Motif/google/${EXTEN}@voice.google.com,,r) ;John Scroggs
exten => 7074681138,1,Dial(Motif/google/${EXTEN}@voice.google.com,,r) ;Juan Gracia
exten => 4155798825,1,Dial(Motif/google/${EXTEN}@voice.google.com,,r) ;Matthew Acadan
exten => 7073913235,1,Dial(Motif/google/${EXTEN}@voice.google.com,,r) ;Nakula Hertz
exten => 7073540123,1,Dial(Motif/google/${EXTEN}@voice.google.com,,r) ;Randy Owen
exten => 7078439962,1,Dial(Motif/google/${EXTEN}@voice.google.com,,r) ;Spike Morelli
exten => 7073914154,1,Dial(Motif/google/${EXTEN}@voice.google.com,,r) ;Steve Setera
exten => 7073913863,1,Dial(Motif/google/${EXTEN}@voice.google.com,,r) ;Tom Johnson
exten => 5109283619,1,Dial(Motif/google/${EXTEN}@voice.google.com,,r) ;Wayne Chen
exten => 7074679948,1,Dial(Motif/google/${EXTEN}@voice.google.com,,r) ;William Koo
exten => 7074890113,1,Dial(Motif/google/${EXTEN}@voice.google.com,,r) ;Teck Hock Lau
exten => 7073915028,1,Dial(Motif/google/${EXTEN}@voice.google.com,,r) ;Doan Van


; master number to trigger the conf bridge
exten => 59998,1,Answer()
 same => n,System(/etc/asterisk/scripts/igdvs-pa.sh)
 same => n,ConfBridge(igdvspa)
 same => n,Hangup()

; number for other phones to join the confbridge
; might need to be moved to cttb context since calls originate from there
; and need to call phones in that range
exten => 69999,1,Answer()
 same => n,ConfBridge(igdvspa)
 same => n,Hangup()
