; CTTB Phone System
; Admin: spike@drba.org

[from-external-vitelity]

exten => 7076217000,1,Goto(drbu-main-menu,s,1)
exten => 7072344709,1,Goto(drbu-main-menu,s,1)
exten => 7072344724,1,Goto(drbu-main-menu,s,1)
exten => 7072344723,1,Goto(drbu-main-menu,s,1)
exten => 7072344726,1,Goto(drbu-main-menu,s,1)
exten => 7074625486,1,Goto(drbu-main-menu,s,1)
