---

  - name: create pxelinux.cfg tftp dir
    file:
      path: "{{ni_tftp_dir}}/pxelinux.cfg"
      state: directory
      owner: root
      group: root
      mode: 0755

  - name: copy files for pxebooting
    copy:
      src: "../../netinstall/files/pxeboot/"
      dest: "{{ni_tftp_dir}}/"
      owner: root
      group: root
      mode: 0644

  - name: create pxe menu dir
    file:
      path: "{{ni_pxe_menu_dir}}"
      state: directory
      owner: root
      group: root
      mode: 0755

  - name: create pxelinux default config file
    template:
      src: pxe/pxelinux-cfg-default-2404.j2
      dest: "{{ni_tftp_dir}}/pxelinux.cfg/default"
      owner: root
      group: root
      mode: 0644
    tags:
      - ni_pxe_menu

  - name: create pxe install menu file for 24.04 images
    template:
      src: pxe/pxe-install-menu-2404.j2
      dest: "{{ni_pxe_menu_dir}}/{{item.os}}-{{item.type}}-{{item.arch}}-{{item.name}}.menu"
      owner: root
      group: root
      mode: 0644
    with_items: "{{ni_2404_images}}"
    tags:
      - ni_pxe_menu
