---

- name: restart nginx
  service:
    name: nginx
    state: restarted

- name: restart php-fpm
  service:
    name: "php{{ storehouse_php_version }}-fpm"
    state: restarted

- name: reload systemd
  systemd:
    daemon_reload: yes
