; CTTB Phone System
; Admin: spike@drba.org

[from-internal-cttb]

; cttb phones 1000-6999
exten => _[1-5]XXX,1,Dial(SIP/${EXTEN},15,t)
 same => n,Followme(${EXTEN})
 same => n,VoiceMail(${EXTEN}@people,u)
 same => n,Hangup()

; example of a callfile + confbridge with just one number/phone allowed
;exten => 59999,1,Answer()
; same => n,GotoIf($["${CALLERID(num)}" != "6999"]?join)
; same => n,System(/etc/asterisk/scripts/igdvs-pa.sh)
; same => n(join),ConfBridge(igdvspa)
; same => n,Hangup()

; ### SERVICE EXTENSIONS ##################33
; putting them here so that all internal phones can access them
; external phones coming in through IVRs etc, will have patterns
; there to avoid access to these numbers

exten => 6900,1,Answer(500)
 same => n,Playback(hello-world)
 same => n,Hangup()

; office 'people' voicemail
exten => 6901,1,Answer(500)
 same => n,VoiceMailMain(${CALLERID(num)}@people)
 same => n,Hangup()

; test voicemail
exten => 6902,1,Answer(500)
 same => n,VoiceMailMain(${CALLERID(num)}@test)
 same => n,Hangup()

; manually move the recorded file to /var/lib/asterisk/sounds
;exten => 6902,1,Wait(2)
; same => n,Record(/tmp/asterisk-recording:gsm)
; same => n,NoOp(${RECORDED_FILE})
; same => n,Wait(2)
; same => n,Playback(/tmp/asterisk-recording)
; same => n,NoOp(${PLAYBACKSTATUS})
; same => n,Wait(1)
; same => n,Hangup()

; used to demo menus and test other extension not permanently wired
exten => 6903,1,Goto(drbu-main-menu,s,1)

; service phones 69XX
exten => _69XX,1,Dial(SIP/${EXTEN},20,t)
 same => n,VoiceMail(${EXTEN}@test,u)
 same => n,Hangup()

include => bogons
