---
#
#  ############### LANGUAGE STUFF ####################
#  Xenial defaults to fcitx
#  install packages required by sogoupinyin
#
#  FCITX default options for users are set in the relevant skel files
#  these are copied over by the look&feel tasks

  # installing hant, which is traditional, but still can type simplified (hans)
  - name: install language packages for en,zh,vi,zhuyin
    apt:
      name: "{{item}}"
      state: present
      install_recommends: no
    with_items:
      - gimp-help-en
      - hunspell-en-au
      - hunspell-en-ca
      - hunspell-en-gb
      - hunspell-en-za
      - hyphen-en-gb
      - hyphen-en-us
      - mythes-en-au
      - mythes-en-us
      - hunspell-vi

  - name: check if libre office is installed
    command: dpkg -l libreoffice-common
    register: libreoffice_installed
    ignore_errors: yes

  - name: install libreoffice language support
    apt:
      name: "{{item}}"
      state: present
      install_recommends: no
    with_items:
      - libreoffice-help-en-gb
      - libreoffice-help-en-us
      - libreoffice-l10n-en-gb
      - libreoffice-l10n-en-za
      - openoffice.org-hyphenation
    when: libreoffice_installed == 1
    tags:
      - libreoffice

  - name: install base fcitx packages
    apt:
      name: "{{item}}"
      state: present
      install_recommends: yes
    with_items:
      - fcitx
      - fcitx-bin
      - fcitx-config-common
      - fcitx-config-gtk2
      - fcitx-data
      - fcitx-frontend-gtk2
      - fcitx-frontend-gtk3
      - fcitx-frontend-qt4
      - fcitx-libs
      - fcitx-libs-qt
      - fcitx-module-dbus
      - fcitx-module-kimpanel
      - fcitx-module-x11
      - fcitx-modules
      # - fcitx-pinyin # we use sogou which seems to work without qimpanel
      - fcitx-table
      - fcitx-table-cangjie
      - fcitx-ui-classic
      - fonts-arphic-ukai
      - fonts-arphic-uming
      - fonts-noto-cjk
      - qtdeclarative5-qtquick2-plugin
      - im-config

  - name: set fcitx as default input method
    command: im-config -n fcitx
    ignore_errors: yes

  - name: install sogoupinyin
    apt:
      name: sogoupinyin
      state: present
  - name: remove sogoupingyin installed mirror
    file:
      path: /etc/apt/sources.list.d/sogoupinyin.list
      state: absent

  # disabled. Most ppl just want the vietnamese keyboard which is built-in
  #- name: install fcitx vietnamese/unikey support
  #  apt:
  #    name: fcitx-unikey
  #    state: present

  - name: install fcitx taiwanese/chewing support
    apt:
      name: fcitx-chewing
      state: present
