---
# Customize look and feel

  - name: setup default account files
    copy:
      src: config/etc-skel/
      dest: /etc/skel/
    tags:
      - desktop

  # gnome-shell: a few buttons at left, status on top. Default in Lubuntu 20.04 install. Not CTTB Lubuntu style, must remove it.
  - name: remove gnome-shell
    apt:
      state: absent
      name: gnome-shell
    tags:
      - desktop
      - packages

  - block: # when icons on the desktop are defined

    - name: create Desktop in skel
      file:
        path: /etc/skel/Desktop
        state: directory
        mode: 0755

    - name: add desktop shortcuts
      copy:
        src: "desktop-shortcuts/{{item}}.desktop"
        dest: /etc/skel/Desktop/
        mode: 0644
        owner: root
        group: root
      loop: "{{ desktop_shortcuts }}"
      when: desktop_shortcuts | length > 0
      tags:
        - desktop
        - shortcuts

  - name: configure lightdm
    template:
      src: lightdm.j2
      dest: /etc/lightdm/lightdm.conf
      mode: 0644
      owner: root
      group: root
    notify: restart lightdm
    tags:
      - lightdm

  - name: configure lightdm gtk greeter
    template:
      src: lightdm-gtk-greeter.j2
      dest: /etc/lightdm/lightdm-gtk-greeter.conf
      mode: 0644
      owner: root
      group: root
    notify: restart lightdm
    tags:
      - lightdm

  - name: ensure lightdm is the active display manager
    shell: echo "/usr/sbin/lightdm" > /etc/X11/default-display-manager
    args:
      creates: /etc/X11/default-display-manager
    tags:
      - lightdm

  - name: copy lightdm avatar image
    copy:
      src: "pics/{{pic_avatar}}"
      dest: /usr/share/lubuntu/images/avatar.png
      mode: 0644
      owner: root
      group: root
    tags:
      - lightdm

  - name: deploy login background image
    copy:
      src: "pics/{{desktop_login_background}}"
      dest: /usr/share/lubuntu/wallpapers/background.jpg
      mode: 0644
      owner: root
      group: root
    tags:
      - lightdm

  - name: copy koha icon
    copy:
      src: pics/koha.gif
      dest: /usr/share/icons/koha.gif
      mode: 0644
      owner: root
      group: root
    tags:
      - desktop
      - icons

  - name: install WhiteSur GTK theme
    unarchive:
      remote_src: yes
      src: "{{ansible_assets_url}}/WhiteSur-gtk-theme.tar.gz"
      dest: /usr/share/themes/
      creates: /usr/share/themes/WhiteSur
      owner: root
      group: root
    tags:
      - desktop
      - theme

  - name: install WhiteSur icon theme
    unarchive:
      remote_src: yes
      src: "{{ansible_assets_url}}/WhiteSur-icon-theme.tar.gz"
      dest: /usr/share/icons/
      creates: /usr/share/icons/WhiteSur
      owner: root
      group: root
    tags:
      - desktop
      - theme

  - name: install WhiteSur cursors
    unarchive:
      remote_src: yes
      src: "{{ansible_assets_url}}/WhiteSur-cursors.tar.gz"
      dest: /usr/share/icons/
      creates: /usr/share/icons/WhiteSur-cursors
      owner: root
      group: root
    tags:
      - desktop
      - theme

  # Lubuntu 20.04: mainly to configure 1 desktop only.
  - name: configure openbox
    template:
      src: openbox-rc.j2
      dest: /etc/xdg/openbox/lxqt-rc.xml
      mode: 0644
      owner: root
      group: root
    tags:
      - desktop

  # Lubuntu 20.04 uses lxqt-panel. System default conf file is at /usr/share/lxqt/panel.conf. This defines the panel's behavior and look and feel.
  - name: configure lxpanel
    template:
      src: lxpanel.j2
      dest: /usr/share/lxqt/panel.conf
      mode: 0644
      owner: root
      group: root
    tags:
      - desktop

  # Use NetworkManager to manage networks instead of the default netplan on 20.04.
  - name: remove netplan's default config file
    file:
      path: /etc/netplan/01-netcfg.yaml
      state: absent
    tags:
      - network

  - name: use NetworkManager instead of netplan to manage networks
    copy:
      src: config/01-network-manager-all.yaml
      dest: /etc/netplan/
      mode: 0644
      owner: root
      group: root
    tags:
      - network

  # Lubuntu 20.04 system default theme is in /usr/share/lxqt/lxqt.conf.
  - name: configure desktop theme
    template:
      src: lxqt-conf.j2
      dest: /usr/share/lxqt/lxqt.conf
      mode: 0644
      owner: root
      group: root
    tags:
      - desktop

  # Lubuntu 20.04 system default icon_theme is in /etc/gtk-3.0/settings.ini.
  - name: configure default icon theme
    template:
      src: gtk-3.0-settings.j2
      dest: /etc/gtk-3.0/settings.ini
      mode: 0644
      owner: root
      group: root
    tags:
      - desktop

  - name: configure lxsession
    template:
      src: lxsession.j2
      dest: /usr/share/lxqt/session.conf
      mode: 0644
      owner: root
      group: root
    tags:
      - desktop

  - name: configure pcmanfm-qt
    template:
      src: pcmanfm.j2
      dest: /usr/share/pcmanfm-qt/lxqt/settings.conf
      mode: 0644
      owner: root
    tags:
      - desktop

  - name: configure lxterminal
    copy:
      src: "config/lxterminal.conf"
      dest: /usr/share/lxterminal/lxterminal.conf
      mode: 0644
      owner: root
      group: root
    tags:
      - desktop
      - lxterminal

  - include_tasks: app-menu.yml
    tags:
      - app_menu

  # administrator acct: set keyboard shortcuts, autostarts an LXTerminal.
  - name: admin acct customization -- prep, creating folders
    file:
      path: '{{ item }}'
      state: directory
      mode: 0755
      owner: administrator
      group: administrator
    loop:
        - /home/administrator/.config/lxqt/
        - /home/administrator/.config/autostart/
    tags:
      - administrator

  - name: admin acct customization -- key shortcuts, autostarts an LXTerminal
    copy:
      src: '{{ item.src }}'
      dest: '{{ item.dest }}'
      mode: 0644
      owner: administrator
      group: administrator
    loop:
        - { src: 'config/etc-skel/.config/lxqt/globalkeyshortcuts.conf', dest: '/home/administrator/.config/lxqt/' }
        - { src: 'config/etc-skel/.config/autostart/LXTerminal.desktop', dest: '/home/administrator/.config/autostart/' }
    tags:
      - administrator
