---
# Dekstop window manager installation and configuration

# TODO:
#   - convert all configs to templates (need to select diff theme, icons etc
#   - convert the rest of the files over, only done common (make windows the default)

  - name: install lubuntu
    apt:
      name: "{{item}}"
      state: present
      install_recommends: yes
      update_cache: yes
      cache_valid_time: 3600
    with_items:
      - lubuntu-core
      - desktop-file-utils
      - dmz-cursor-theme
      - evince
      - file-roller
      - galculator
      - indicator-application
      - indicator-application-gtk2
      - leafpad
      - light-locker
      - light-locker-settings
      - lightdm-gtk-greeter-settings
      - lubuntu-default-session
      - lxappearance
      - lxappearance-obconf
      - lxinput
      - lxlauncher
      - lxpanel-indicator-applet-plugin
      - lxrandr
      - lxsession-default-apps
      - lxsession-logout
      - lxshortcut
      - lxtask
      - lxterminal
      - obconf
      - pm-utils
      - scrot
      - simple-scan
      - xdg-user-dirs
      - xfce4-power-manager
      - xz-utils
      - policykit-1
      - policykit-1-gnome
      - libpolkit-agent-1-0
      - libpolkit-gobject-1-0
      - libpolkit-backend-1-0
      - libpolkit-qt-1-1
      - libpolkit-qt5-1-1
      - network-manager
      - network-manager-gnome
      - system-tools-backends
      - gnome-system-tools
