---

  - name: install additional software
    apt:
      state: present
      install_recommends: no
      name:
      - audacious
      - audacity
      - blender
      - cups-client
      - gimp
      - imagemagick-6.q16hdri
      - inkscape
      - kdenlive
      - pavucontrol-qt
      - python-is-python3
      - python3-pip
      - ubuntu-restricted-addons
      - ubuntu-restricted-extras
      - vlc
    tags:
      - packages

  - name: install desktop sw requested for this box
    apt:
      name: "{{additional_desktop_sw | default([])}}"
      state: present
    tags:
      - packages
      - additional_desktop_sw

  # removing bunch of sw I don't need
  - name: remove other apps
    apt:
      state: absent
      purge: yes
      name:
      - cups-browsed
      - deja-dup
      - eog
      - galculator
      - gdb
      - gnome-keyring
      - gnome-logs
      - midori      # a lightweight web browser in Ubuntu 20.04 minimal ISO.
      - nautilus
      - sylpheed*
      - update-manager
      - update-notifier
      - update-notifier-common     # Will be installed by "ubuntu-restricted-extras".
    tags:
      - packages

   # Purging failed at preseed time since it's removing a file /.../whoopsie-id is that'll be created until the 1st run.
  - name: purge whoopsie
    apt:
      state: absent
      purge: yes
      name:
      - whoopsie
    ignore_errors: true
    tags:
      - packages

  # Seems no need to have snap store.
  - name: remove snap-store
    snap:
      name: snap-store
      state: absent
    tags:
      - packages

  - include_tasks: sw-office.yml
    tags:
      - office

  - include_tasks: sw-browser.yml
    tags:
      - browser

  - include_tasks: sw-thunderbird.yml
    when: thunderbird == true
    tags:
      - thunderbird

  - include_tasks: sw-vscode.yml
    tags:
      - vscode

  - name: upgrade Zoom client
    apt:
      deb: "{{ansible_assets_url}}/zoom_amd64.deb"
      only_upgrade: true
    register: zoom_upgraded
    tags:
      - zoom

  - name: install Zoom client for the 1st time
    apt:
      deb: "{{ansible_assets_url}}/zoom_amd64.deb"
    when: zoom_upgraded is not changed
    tags:
      - zoom

  - name: upgrade Skype
    apt:
      deb: "{{ansible_assets_url}}/skypeforlinux-64.deb"
      only_upgrade: true
    register: skype_upgraded
    when: skype == true
    tags:
      - skype

  - name: install Skype for the 1st time
    apt:
      deb: "{{ansible_assets_url}}/skypeforlinux-64.deb"
    when: (skype == true) and (skype_upgraded is not changed)
    tags:
      - skype
