---

ni_root_dir: /srv/netinstall
ni_tftp_dir: "{{ni_root_dir}}"
ni_preseed_dir: "{{ni_root_dir}}/preseed"
ni_pxe_menu_dir: "{{ni_root_dir}}/menu"
ni_isos_cache_dir: "{{ni_root_dir}}"
ni_www_path: "/var/www/html/netinstall"
ni_memtest_iso_url: "{{ansible_assets_url}}/isos/memtest86-7.3.iso"

ni_images:
  - name: xenial
    os: ubuntu
    type: mini
    arch: amd64
    url: "{{ansible_assets_url}}/isos/ubuntu-mini-xenial-amd64.iso"
    preseed:
      - name: default
        description: "Default Installation" 
        kernel_path: linux
        initrd_path: initrd.gz
        partman: simple
      - name: server
        description: "Server Installation" 
        kernel_path: linux
        initrd_path: initrd.gz
        tasksel: server
        partman: simple
      - name: "srv-raid1"
        description: "Server raid 1" 
        kernel_path: linux
        initrd_path: initrd.gz
        tasksel: server
        partman: raid1
      - name: "srv-raid6"
        description: "Server Raid 10" 
        kernel_path: linux
        initrd_path: initrd.gz
        tasksel: server
        partman: raid6
      - name: desktop
        description: "Desktop Installation" 
        kernel_path: linux
        initrd_path: initrd.gz
        tasksel: lubuntu-desktop
        partman: simple
  - name: xenial
    os: ubuntu
    type: mini
    arch: i386
    url: "{{ansible_assets_url}}/isos/ubuntu-mini-xenial-i386.iso"
    preseed:
      - name: default
        description: "Default Installation" 
        kernel_path: linux
        initrd_path: initrd.gz
        partman: simple
      - name: server
        description: "Server Installation" 
        kernel_path: linux
        initrd_path: initrd.gz
        tasksel: server
        partman: simple
      - name: desktop
        description: "Desktop Installation" 
        kernel_path: linux
        initrd_path: initrd.gz
        tasksel: lubuntu-desktop
        partman: simple
