---

  - block:
        - name: install ntp
          apt:
            state: present
            install_recommends: no
            name:
            - ntp

        - name: install ntp.conf from template
          template:
            src: ntp.j2
            dest: /etc/ntp.conf
            mode: 0644
            owner: root
            group: root
          notify:
          - restart ntp
          tags:
            - ntp_cfg

        - name: disable systemd-timesyncd
          systemd:
            name: systemd-timesyncd
            state: stopped
            enabled: no
          ignore_errors: yes
          # When running ansible for post-installation of a new PC, there is no systemd-timesyncd, so ignore the errors.
    when: ansible_virtualization_type != "lxc"

  - block:
    - name: remove ntp
      apt:
        state: absent
        purge: yes
        name:
        - ntp
    when: ansible_virtualization_type == "lxc"
