---

  - name: ensure rsyslog is installed, should be already
    apt:
      name: rsyslog
      state: present

  - name: setup logging configuration
    copy:
      src: rsyslog.conf
      dest: /etc/rsyslog.conf
      mode: 0644
      owner: root
      group: root
      force: yes
    notify:
    - restart rsyslog
    tags:
      - central_logging_server

