drbu-sw-cslab-w-pc1 mac_addr=2c:41:38:8f:80:35 ansible_address=10.11.16.13
drbu-sw-cslab-w-pc2 mac_addr=2c:41:38:8f:d8:ec ansible_address=10.11.16.14
drbu-sw-cslab-w-pc3 mac_addr=3c:d9:2b:78:ff:ba ansible_address=10.11.16.15
drbu-sw-cslab-m-pc1 mac_addr=3c:d9:2b:5b:d1:3c ansible_address=10.11.16.16
drbu-sw-cslab-m-pc2 mac_addr=2c:41:38:8f:d7:c6 ansible_address=10.11.16.17
drbu-sw-cslab-m-pc3 mac_addr=2c:41:38:8a:b2:8c ansible_address=10.11.16.18
drbu-cdorm-lab-pc1 mac_addr=00:24:81:07:4d:79 ansible_address=10.11.16.7
drbu-cdorm-lab-pc2 mac_addr=a0:48:1c:8e:06:bd ansible_address=10.11.16.8
drbu-cdorm-lab-pc3 mac_addr=00:23:7d:b8:5d:36 ansible_address=10.11.16.9
drbu-cdorm-lab-pc4 mac_addr=00:24:81:06:f4:c1 ansible_address=10.11.16.10
drbu-cdorm-lab-pc5 mac_addr=e4:54:e8:4f:ba:df ansible_address=10.11.16.27
dvbs-cc-m401 mac_addr=6c:c2:17:23:06:35 ansible_address=10.11.28.120
dvbs-cc-yearbook-pc mac_addr=e8:40:f2:05:a5:43 ansible_address=10.11.11.178
dvbs-cc-pc1-dell mac_addr=30:d0:42:f7:f9:fa ansible_address=10.11.10.151
dvbs-cc-pc2-dell mac_addr=30:d0:42:f7:fa:0b ansible_address=10.11.10.152
dvbs-cc-pc3-dell mac_addr=30:d0:42:f7:fb:4f ansible_address=10.11.10.153
dvbs-cc-pc4-dell mac_addr=30:d0:42:f8:05:d6 ansible_address=10.11.10.154
dvbs-cc-pc5-dell mac_addr=30:d0:42:f7:fc:56 ansible_address=10.11.10.155
dvbs-cc-pc6-dell mac_addr=30:d0:42:f7:fb:0a ansible_address=10.11.10.156
dvbs-cc-pc7-dell mac_addr=30:d0:42:f7:fb:f8 ansible_address=10.11.10.157
dvbs-cc-pc8-dell mac_addr=30:d0:42:f7:fa:1f ansible_address=10.11.10.158
dvbs-cc-pc9-dell mac_addr=30:d0:42:f7:fb:30 ansible_address=10.11.10.159
dvbs-cc-pc10-dell mac_addr=30:d0:42:f7:fc:76 ansible_address=10.11.10.160
dvbs-cc-pc11 mac_addr=6c:3b:e5:10:9d:fe ansible_address=10.11.10.161
dvbs-cc-pc12 mac_addr=74:46:a0:a5:a7:88 ansible_address=10.11.10.162
dvbs-cc-pc13 mac_addr=6c:3b:e5:3d:01:ba ansible_address=10.11.10.163
dvbs-cc-pc14 mac_addr=d4:c9:ef:f1:fc:a7 ansible_address=10.11.10.164
dvbs-cc-pc15 mac_addr=74:46:a0:b4:ef:38 ansible_address=10.11.10.165
dvbs-cc-pc16 mac_addr=30:5a:3a:7a:e2:8a ansible_address=10.11.10.166
dvbs-cc-pc17 mac_addr=00:15:f2:d7:83:e3 ansible_address=10.11.10.167
dvbs-cc-pc18-w mac_addr=94:e2:3c:3d:54:87 ansible_address=10.11.10.168
dvbs-cc-pc19-hp mac_addr=f4:ce:46:f4:c2:5a ansible_address=10.11.10.169
dvbs-lab01 mac_addr=30:d0:42:f8:03:0c ansible_address=10.11.10.1
dvbs-lab02 mac_addr=30:d0:42:f7:f9:70 ansible_address=10.11.10.2
dvbs-lab03 mac_addr=30:d0:42:f7:fb:d1 ansible_address=10.11.10.3
dvbs-lab04 mac_addr=30:d0:42:f7:fb:51 ansible_address=10.11.10.4
dvbs-lab05 mac_addr=30:d0:42:f8:06:6a ansible_address=10.11.10.5
dvbs-lab06 mac_addr=30:d0:42:f8:06:d2 ansible_address=10.11.10.6
dvbs-lab07 mac_addr=30:d0:42:f7:fb:05 ansible_address=10.11.10.7
dvbs-lab08 mac_addr=30:d0:42:f5:5f:41 ansible_address=10.11.10.8
dvbs-lab08 mac_addr=10:60:4b:71:e5:c0 ansible_address=10.11.10.8
dvbs-lab09 mac_addr=30:d0:42:f8:02:e6 ansible_address=10.11.10.9
dvbs-lab10 mac_addr=10:60:4b:80:79:26 ansible_address=10.11.10.10
dvbs-lab11 mac_addr=f8:bc:12:92:1a:ac ansible_address=10.11.10.11
dvbs-lab12 mac_addr=c8:1f:66:4b:53:b5 ansible_address=10.11.10.12
dvbs-lab13 mac_addr=c8:1f:66:2b:a0:2b ansible_address=10.11.10.13
dvbs-lab14 mac_addr=18:03:73:ae:cc:6f ansible_address=10.11.10.14
dvbs-lab15 mac_addr=10:60:4b:86:4f:26 ansible_address=10.11.10.15
dvbs-lab16 mac_addr=2c:44:fd:22:0d:fc ansible_address=10.11.10.16
dvbs-lab17-eth mac_addr=fc:34:97:71:4e:29 ansible_address=10.11.10.50
dvbs-lab17-wifi mac_addr=00:e9:3a:8c:e7:5b ansible_address=10.11.10.51
dvbs-lab18-eth mac_addr=f0:2f:74:26:d1:f6 ansible_address=10.11.10.52
dvbs-lab18-wifi mac_addr=20:4e:f6:f8:d4:0d ansible_address=10.11.10.53
dvbs-lab19-eth mac_addr=f0:2f:74:26:d2:1b ansible_address=10.11.10.54
dvbs-lab19-wifi mac_addr=20:4e:f6:f8:7b:89 ansible_address=10.11.10.55
dvbs-lab20-eth mac_addr=f0:2f:74:26:d2:1a ansible_address=10.11.10.56
dvbs-lab20-wifi mac_addr=20:4e:f6:f8:7b:8b ansible_address=10.11.10.57
dvbs-lab21-eth mac_addr=f0:2f:74:25:b1:5a ansible_address=10.11.10.58
dvbs-lab21-wifi mac_addr=00:e9:3a:8c:d6:0d ansible_address=10.11.10.59
dvbs-lab22-eth mac_addr=f0:2f:74:26:d1:54 ansible_address=10.11.10.60
dvbs-lab22-wifi mac_addr=20:4e:f6:f8:d3:39 ansible_address=10.11.10.61
dvbs-lib1 mac_addr=00:23:24:20:af:9a ansible_address=10.11.10.21
dvbs-lib2 mac_addr=2c:27:d7:29:f6:65 ansible_address=10.11.10.22
dvbs-lib3 mac_addr=78:ac:c0:b2:89:a8 ansible_address=10.11.10.23
dvgs-lab1 mac_addr=30:d0:42:f8:02:7f ansible_address=10.11.9.21
dvgs-lab2 mac_addr=30:d0:42:f7:f2:06 ansible_address=10.11.9.22
dvgs-lab3 mac_addr=30:d0:42:f8:03:1a ansible_address=10.11.9.23
dvgs-lab4 mac_addr=30:d0:42:f7:fb:bf ansible_address=10.11.9.24
dvgs-lab5 mac_addr=30:d0:42:f5:5e:ba ansible_address=10.11.9.25
dvgs-lab6 mac_addr=30:d0:42:f7:fb:2c ansible_address=10.11.9.26
dvgs-lab7 mac_addr=10:60:4b:71:e5:c0 ansible_address=10.11.9.27
dvgs-lab7 mac_addr=30:d0:42:f8:05:cd ansible_address=10.11.9.27
dvgs-lab8 mac_addr=10:60:4b:7d:5e:28 ansible_address=10.11.9.28
dvgs-lab9 mac_addr=f4:ce:46:f4:cf:3c ansible_address=10.11.9.29
dvgs-lab1 mac_addr=30:d0:42:f8:02:7f ansible_address=10.11.9.21
dvgs-lab2 mac_addr=30:d0:42:f7:f2:06 ansible_address=10.11.9.22
dvgs-lab3 mac_addr=30:d0:42:f8:03:1a ansible_address=10.11.9.23
dvgs-lab4 mac_addr=30:d0:42:f7:fb:bf ansible_address=10.11.9.24
dvgs-lab5 mac_addr=30:d0:42:f5:5e:ba ansible_address=10.11.9.25
dvgs-lab6 mac_addr=30:d0:42:f7:fb:2c ansible_address=10.11.9.26
dvgs-lab7 mac_addr=10:60:4b:71:e5:c0 ansible_address=10.11.9.27
dvgs-lab7 mac_addr=30:d0:42:f8:05:cd ansible_address=10.11.9.27
dvgs-lab8 mac_addr=10:60:4b:7d:5e:28 ansible_address=10.11.9.28
dvgs-lab9 mac_addr=f4:ce:46:f4:cf:3c ansible_address=10.11.9.29
dvgs-dorm-hp-aio1 mac_addr=a0:8c:fd:23:b5:d1 ansible_address=10.11.9.81
dvgs-dorm-hp-aio1-w mac_addr=ac:2b:6e:50:3f:52 ansible_address=10.11.9.82
dvgs-dorm-hp-aio2 mac_addr=a0:8c:fd:20:ea:f7 ansible_address=10.11.9.83
dvgs-dorm-hp-aio2-w mac_addr=ac:2b:6e:48:38:02 ansible_address=10.11.9.84
dvgs-dorm-dell-aio2 mac_addr=30:d0:42:f8:04:5e ansible_address=10.11.9.85
dvgs-dorm-dell-aio3 mac_addr=30:d0:42:f7:fb:c2 ansible_address=10.11.9.86
dvgs-dorm-dell-win14 mac_addr=20:88:10:64:78:43 ansible_address=10.11.9.87
dvgs-dorm-dell-win14-w mac_addr=48:ad:9a:70:d6:72 ansible_address=10.11.9.88
dvgs-dorm-dell-win15 mac_addr=20:88:10:64:77:6e ansible_address=10.11.9.89
dvgs-dorm-dell-win15-w mac_addr=48:ad:9a:70:d6:59 ansible_address=10.11.9.90
dvgs-dorm-win1 mac_addr=9c:5a:44:92:5e:15 ansible_address=10.11.9.141
dvgs-dorm-win1-w mac_addr=f8:e4:e3:42:b2:b5 ansible_address=10.11.9.142
dvgs-dorm-win2 mac_addr=9c:5a:44:92:5c:66 ansible_address=10.11.9.143
dvgs-dorm-win2-w mac_addr=f8:e4:e3:41:51:5e ansible_address=10.11.9.144
dvgs-dorm-lenovo3 mac_addr=9c:5a:44:92:5f:3e ansible_address=10.11.9.145
dvgs-dorm-lenovo3-w mac_addr=f8:e4:e3:42:52:c5 ansible_address=10.11.9.146
dvgs-dorm-win7 mac_addr=9c:5a:44:92:5c:5f ansible_address=10.11.9.169
dvgs-dorm-win7-w mac_addr=0c:7a:15:ce:72:a0 ansible_address=10.11.9.170
dvgs-dorm-win8 mac_addr=9c:5a:44:92:c7:f5 ansible_address=10.11.9.171
dvgs-dorm-win8-w mac_addr=0c:7a:15:cd:ae:6f ansible_address=10.11.9.172
dvgs-dorm-win9 mac_addr=9c:5a:44:92:c9:17 ansible_address=10.11.9.173
dvgs-dorm-win9-w mac_addr=0c:7a:15:ce:1f:76 ansible_address=10.11.9.174
dvgs-dorm-win10 mac_addr=9c:5a:44:92:ca:b1 ansible_address=10.11.9.175
dvgs-dorm-win10-w mac_addr=0c:7a:15:27:7e:ff ansible_address=10.11.9.176
dvgs-dorm-win11 mac_addr=9c:5a:44:94:76:08 ansible_address=10.11.9.177
dvgs-dorm-win12 mac_addr=9c:5a:44:93:8e:7d ansible_address=10.11.9.179
dvgs-dorm-win12-w mac_addr=b8:9a:2a:07:22:77 ansible_address=10.11.9.180
dvgs-dorm-win13 mac_addr=9c:5a:44:94:76:06 ansible_address=10.11.9.181
dvgs-dorm-win13-w mac_addr=b8:9a:2a:07:00:a8 ansible_address=10.11.9.182

[drbu_cslab]
drbu-sw-cslab-w-pc1 
drbu-sw-cslab-w-pc2
drbu-sw-cslab-w-pc3
drbu-sw-cslab-m-pc1 
drbu-sw-cslab-m-pc2 
drbu-sw-cslab-m-pc3

[drbu_cdorm]
drbu-cdorm-lab-pc1
drbu-cdorm-lab-pc2
drbu-cdorm-lab-pc3
drbu-cdorm-lab-pc4
drbu-cdorm-lab-pc5

[dvbs_community_center:vars]
# TODO: Insert all shared group varibles.

[dvbs_community_center]
dvbs-cc-m401 
dvbs-cc-yearbook-pc 
dvbs-cc-pc1-dell 
dvbs-cc-pc2-dell 
dvbs-cc-pc3-dell 
dvbs-cc-pc4-dell 
dvbs-cc-pc5-dell 
dvbs-cc-pc6-dell 
dvbs-cc-pc7-dell 
dvbs-cc-pc8-dell 
dvbs-cc-pc9-dell 
dvbs-cc-pc10-dell 
dvbs-cc-pc11 
dvbs-cc-pc12 
dvbs-cc-pc13 
dvbs-cc-pc14 
dvbs-cc-pc15 
dvbs-cc-pc16 
dvbs-cc-pc17 
dvbs-cc-pc18-w 
dvbs-cc-pc19-hp 

[dvbs_cslab:vars]
# TODO: Insert all shared group varibles.

[dvbs_cslab]
dvbs-lab01 
dvbs-lab02 
dvbs-lab03 
dvbs-lab04 
dvbs-lab05 
dvbs-lab06 
dvbs-lab07 
dvbs-lab08 
dvbs-lab08 
dvbs-lab09 
dvbs-lab10 
dvbs-lab11 
dvbs-lab12 
dvbs-lab13 
dvbs-lab14 
dvbs-lab15 
dvbs-lab16 
dvbs-lab17-eth 
dvbs-lab17-wifi 
dvbs-lab18-eth 
dvbs-lab18-wifi 
dvbs-lab19-eth 
dvbs-lab19-wifi 
dvbs-lab20-eth 
dvbs-lab20-wifi 
dvbs-lab21-eth 
dvbs-lab21-wifi 
dvbs-lab22-eth 
dvbs-lab22-wifi 

[dvbs_library:vars]
# TODO: Insert all shared group varibles.

[dvbs_library]
dvbs-lib1 
dvbs-lib2 
dvbs-lib3 

[dvgs_cslab:vars]
# TODO: Insert all shared group varibles.

[dvgs_cslab]
dvgs-lab1 
dvgs-lab2 
dvgs-lab3 
dvgs-lab4 
dvgs-lab5 
dvgs-lab6 
dvgs-lab7 
dvgs-lab7 
dvgs-lab8 
dvgs-lab9 
dvgs-lab1 
dvgs-lab2 
dvgs-lab3 
dvgs-lab4 
dvgs-lab5 
dvgs-lab6 
dvgs-lab7 
dvgs-lab7 
dvgs-lab8 
dvgs-lab9 

[dvgs_dormitory:vars]
# TODO: Insert all shared group varibles.


[dvgs_dormitory]
dvgs-dorm-hp-aio1 
dvgs-dorm-hp-aio1-w 
dvgs-dorm-hp-aio2 
dvgs-dorm-hp-aio2-w 
dvgs-dorm-dell-aio2 
dvgs-dorm-dell-aio3 
dvgs-dorm-dell-win14 
dvgs-dorm-dell-win14-w 
dvgs-dorm-dell-win15 
dvgs-dorm-dell-win15-w 
dvgs-dorm-win1 
dvgs-dorm-win1-w 
dvgs-dorm-win2 
dvgs-dorm-win2-w 
dvgs-dorm-lenovo3 
dvgs-dorm-lenovo3-w 
dvgs-dorm-win7 
dvgs-dorm-win7-w 
dvgs-dorm-win8 
dvgs-dorm-win8-w 
dvgs-dorm-win9 
dvgs-dorm-win9-w 
dvgs-dorm-win10 
dvgs-dorm-win10-w 
dvgs-dorm-win11 
dvgs-dorm-win12 
dvgs-dorm-win12-w 
dvgs-dorm-win13 
dvgs-dorm-win13-w 

[dvgs_hosts:children]
dvgs_cslab
dvgs_dormitory

[dvbs_hosts:children]
dvbs_community_center
dvbs_cslab
dvbs_library

[drbu_hosts:children]
drbu_cslab
drbu_cdorm
 
[cttb_hosts:children]
drbu_hosts
dvgs_hosts
dvbs_hosts

