---

  - name: install autofs
    apt:
      name: autofs
      state: present
      install_recommends: yes

  # do not configure it if no nfs homes/export vars are provided
  - block:
    - name: copy autofs.conf
      copy:
        src: autofs.conf
        dest: /etc/autofs.conf
        owner: root
        group: root
        mode: 0640
        force: yes
      notify:
        - restart autofs

    - name: copy auto.master
      copy:
        src: auto.master
        dest: /etc/auto.master
        owner: root
        group: root
        mode: 0640
        force: yes
      notify:
        - restart autofs

    - name: setup auto.nfs
      template:
        src: auto.nfs.j2
        dest: /etc/auto.nfs
        owner: root
        group: root
        mode: 0640
      notify:
        - restart autofs
    when: nfs_homes_host is defined and nfs_homes_export is defined
