---

filter_ip: 127.0.0.1 #need to be replaced or E2G won't be available on the network
proxy_ip: 127.0.0.1
groups_number: 1 # by default have only one filter group to send all traffic to

filtering_groups:
  - name: default
    num: 1 # must be unique
    ips: [] # ips or ranges to assign machines to this group. Default group is empty as a catch-all
    naughtynesslimit: 50 # default of 50 is for young kids
    bypass: 0 # 0 to disable, or num seconds bypass link is valid for
    disablecontentscan: 'on' # no AV scanning for now
    deepurlanalysis: 'on'
    sslmitm: 'off'
    reportinglevel: 3 # default, html page
    overrides: # lists to override per group
      - exceptionsitelist

# lists we want to be able to modify/override
filtering_groups_lists:
  - addheaderregexplist
  - bannedphraselist
  - bannedregexpurllist
  - bannedsitelist
  - bannedurllist
  - exceptionextensionlist
  - exceptionphraselist
  - exceptionregexpurllist
  - exceptionsitelist
  - exceptionurllist
  - greysitelist
  - greyurllist
  - urlregexplist
  - weightedphraselist

# lists that we don't care to modify and can be always default
default_lists:
  - authexceptionsitelist
  - authexceptionurllist
  - bannedextensionlist
  - bannedmimetypelist
  - bannedregexpheaderlist
  - bannedsitelistwithbypass
  - contentregexplist
  - exceptionfilesitelist
  - exceptionfileurllist
  - exceptionmimetypelist
  - headerregexplist
  - sslsiteregexplist

# global lists we want all groups to include
cttb_global_lists:
  - addheaderregexplist
  - bannedphraselist
  - bannedregexpurllist
  - bannedsitelist
  - exceptionextensionlist
  - exceptionregexpurllist
  - exceptionsitelist
  - urlregexplist
  - weightedphraselist

enablessl: 'off'
