---

# lightdm configuration
lightdm_hide_users: false

# sw install
wpsoffice: false
libreoffice: true
openoffice: false
firefox: true
chrome: true
dropbox: false
skype: false

# look and feel
desktop_shortcuts: false
desktop_theme: Lubuntu-default
icons_theme: windos10-icons
pic_avatar: avatar-cttb.png
pic_bg: bg-windos10.jpg
start_icon: windos10-icons/scalable/places/start-here-symbolic.svg
