---
  # workaround for  https://bugs.launchpad.net/ubuntu/+source/xserver-xorg-video-intel/+bug/1568604
  - name: Download xorg intel from yakkety (64bits)
    get_url: 
      url: http://launchpadlibrarian.net/271461135/xserver-xorg-video-intel_2.99.917+git20160706-1ubuntu1_amd64.deb
      dest: /root/xorg-intel-yakkety.deb
    when: ansible_architecture == 'amd64' or ansible_architecture == 'x86_64'
    tags:
      - fixmouse
  - name: Download xorg intel from yakkety (32bits)
    get_url: 
      url: http://launchpadlibrarian.net/271460878/xserver-xorg-video-intel_2.99.917+git20160706-1ubuntu1_i386.deb
      dest: /root/xorg-intel-yakkety.deb
    when: ansible_architecture != 'amd64' and ansible_architecture != 'x86_64'
    tags:
      - fixmouse
  - name: Install xorg intel from yakkety
    apt:
      deb: /root/xorg-intel-yakkety.deb
    tags:
      - fixmouse

