---
# Customize look and feel

  - name: setup default account files
    copy:
      src: config/etc-skel/
      dest: /etc/skel/

  - block: # when icons on the desktop are defined

    - name: create Desktop in skel
      file:
        path: /etc/skel/Desktop
        state: directory
        mode: 0755
    
    - name: add desktop shortcuts
      copy:
        src: "desktop-shortcuts/{{item}}.desktop"
        dest: /etc/skel/Desktop/
        mode: 0644
        owner: root
        group: root
      with_items: "{{desktop_shortcuts}}"

    when: desktop_shortcuts
    tags:
      - shortcuts

  - name: configure lightdm
    template:
      src: lightdm.j2
      dest: /etc/lightdm/lightdm.conf
      mode: 0644
      owner: root
      group: root
    tags:
      - lightdm

  - name: configure lightdm gtk greeter
    template:
      src: lightdm-gtk-greeter.j2
      dest: /etc/lightdm/lightdm-gtk-greeter.conf
      mode: 0644
      owner: root
      group: root
    tags:
      - lightdm

  - name: copy lightdm avatar image
    copy:
      src: "pics/{{pic_avatar}}"
      dest: /usr/share/lubuntu/images/avatar.png
      mode: 0644
      owner: root
      group: root
    tags:
      - lightdm

  - name: deploy image background
    copy:
      src: "pics/{{pic_bg}}"
      dest: /usr/share/lubuntu/wallpapers/background.jpg
      mode: 0644
      owner: root
      group: root
    tags:
      - lightdm

  - name: copy koha icon
    copy:
      src: pics/koha.gif
      dest: /usr/share/icons/koha.gif
      mode: 0644
      owner: root
      group: root
    tags:
      - icons

  #- name: add noobslab mirror key
    #apt_key:
      #keyserver: keyserver.ubuntu.com
      #id: "0xF59EAE4D"

  #- name: Add noobslab icon repository
    #apt_repository:
      #repo: "deb {{deb_mirror}}/noobslab-icons {{ansible_distribution_release}} main"
      #state: present

  #- name: Add noobslab theme repository
    #apt_repository:
      #repo: "deb {{deb_mirror}}/noobslab-themes {{ansible_distribution_release}} main"
      #state: present

  #- name: install noobs icons
    #apt:
      #name: "{{item}}"
      #state: present
      #install_recommends: no
    #with_items:
      #- super-flat-remix-icons
      #- vertex-icons
      #- arc-icons

  - name: install windos10 icons
    unarchive:
      remote_src: yes
      src: "{{ansible_assets_url}}/windos10-icons-custom.tar.gz"
      dest: /usr/share/icons/
      owner: root
      group: root

  - name: install noobslab windos10-theme
    apt:
      name: windos-10-themes
      state: present

  - name: configure openbox
    template:
      src: openbox-rc.j2
      dest: /usr/share/lubuntu/openbox/rc.xml
      mode: 0644
      owner: root
      group: root

  # from testing the xdg directory is there but not used in this case
  - name: configure lxpanel
    template:
      src: lxpanel.j2
      dest: /usr/share/lxpanel/profile/Lubuntu/panels/panel
      mode: 0644
      owner: root
      group: root

  - name: configure lxsession
    template:
      src: lxsession.j2
      dest: /etc/xdg/lxsession/Lubuntu/desktop.conf
      mode: 0644
      owner: root
      group: root

  - name: configure pcmanfm
    template:
      src: pcmanfm.j2
      dest: /etc/xdg/pcmanfm/lubuntu/pcmanfm.conf
      mode: 0644
      owner: root
      group: root
