---
# Customize look and feel

  - name: setup default account files
    copy:
      src: config/etc-skel/
      dest: /etc/skel/

  # gnome-shell: a few buttons at left, status on top. Default in Lubuntu 20.04 install. Not CTTB Lubuntu style, must remove it.
  - name: remove gnome-shell
    apt:
      state: absent
      name: gnome-shell

  - block: # when icons on the desktop are defined

    - name: create Desktop in skel
      file:
        path: /etc/skel/Desktop
        state: directory
        mode: 0755
    
    - name: add desktop shortcuts
      copy:
        src: "desktop-shortcuts/{{item}}.desktop"
        dest: /etc/skel/Desktop/
        mode: 0644
        owner: root
        group: root
      with_items: "{{desktop_shortcuts}}"

    when: desktop_shortcuts
    tags:
      - shortcuts

  - name: configure lightdm
    template:
      src: lightdm.j2
      dest: /etc/lightdm/lightdm.conf
      mode: 0644
      owner: root
      group: root
    tags:
      - lightdm

  - name: configure lightdm gtk greeter
    template:
      src: lightdm-gtk-greeter.j2
      dest: /etc/lightdm/lightdm-gtk-greeter.conf
      mode: 0644
      owner: root
      group: root
    tags:
      - lightdm

  - name: copy lightdm avatar image
    copy:
      src: "pics/{{pic_avatar}}"
      dest: /usr/share/lubuntu/images/avatar.png
      mode: 0644
      owner: root
      group: root
    tags:
      - lightdm

  - name: deploy image background
    copy:
      src: "pics/{{pic_bg}}"
      dest: /usr/share/lubuntu/wallpapers/background.jpg
      mode: 0644
      owner: root
      group: root
    tags:
      - lightdm

  - name: copy koha icon
    copy:
      src: pics/koha.gif
      dest: /usr/share/icons/koha.gif
      mode: 0644
      owner: root
      group: root
    tags:
      - icons

  - name: install windos10 icons
    unarchive:
      remote_src: yes
      src: "{{ansible_assets_url}}/windos10-icons-custom.tar.gz"
      dest: /usr/share/icons/
      # Use "creates" to skip copying if already exists:
      creates: /usr/share/icons/windos10-icons
      owner: root
      group: root

  # Lubuntu 20.04: mainly to configure 1 desktop only.
  - name: configure openbox
    template:
      src: openbox-rc.j2
      #dest: /usr/share/lubuntu/openbox/rc.xml    # For Lubuntu 16.04.
      dest: /etc/xdg/openbox/lxqt-rc.xml          # For Lubuntu 20.04.
      mode: 0644
      owner: root
      group: root

  # Lubuntu 20.04 uses lxqt-panel. System default conf file is at /usr/share/lxqt/panel.conf. This defines the panel's behavior and look and feel.
  - name: configure lxpanel
    template:
      src: lxpanel.j2
      dest: /usr/share/lxqt/panel.conf
      mode: 0644
      owner: root
      group: root

  # Lubuntu 20.04 system default icons_theme is in /usr/share/lxqt/lxqt.conf.
  - name: configure lxpanel
    template:
      src: lxqt-conf.j2
      dest: /usr/share/lxqt/lxqt.conf
      mode: 0644
      owner: root
      group: root

  - name: configure lxsession
    template:
      src: lxsession.j2
      dest: /usr/share/lxqt/session.conf
      mode: 0644
      owner: root
      group: root

  - name: configure pcmanfm
    template:
      src: pcmanfm.j2
      dest: /usr/share/pcmanfm-qt/lxqt/settings.conf
      mode: 0644
      owner: root

  - name: fix a desktop file that missed an ending newline character
    shell: cd /usr/share/applications; FILE1=light-locker-settings.desktop; tail -c1 $FILE1 | read -r _ || echo >> $FILE1
    tags:
      - customize_app_menu
      - add_newline

  - include: app-menu.yml
    tags:
      - app_menu
