---

  - name: install lubuntu
    apt:
      state: latest
      install_recommends: no
      name:
      - alsa-utils
      - alsamixergui
      - desktop-file-utils
      - dmz-cursor-theme
      - evince
      - file-roller
      - galculator
      - gnome-system-tools
      - indicator-application
      #- leafpad       # Absent in 20.04.
      - libpolkit-agent-1-0
      #- libpolkit-backend-1-0
      - libpolkit-gobject-1-0
      #- libpolkit-qt-1-1
      - libpolkit-qt5-1-1
      - lightdm-gtk-greeter-settings
      - light-locker
      - light-locker-settings
      - lubuntu-artwork
      #- lubuntu-core   # Absent in 20.04.
      #- lubuntu-default-session   # Absent in 20.04.
      - lubuntu-default-settings
      #- lubuntu-lxpanel-icons     # Absent in 20.04.
      - lxappearance
      - lxappearance-obconf
      - lxinput
      - lxlauncher
      #- lxpanel-indicator-applet-plugin   # Absent in 20.04.
      - lxrandr
      - lxsession-default-apps
      - lxsession-logout
      #- lxshortcut   # Absent in 20.04.
      #- lxtask   # Unneeded.
      - lxterminal
      - network-manager
      - network-manager-gnome
      - obconf
      #- plymouth-theme-lubuntu-logo
      #- plymouth-theme-lubuntu-text
      - pm-utils
      - policykit-1
      - policykit-1-gnome
      - scrot
      - simple-scan
      - system-tools-backends
      - xdg-user-dirs
      - xfce4-power-manager
      - xz-utils

    # overrides lubuntu default triggering the LXDE session to be loaded which
    # in turns make lxde pick up the wrong configs.
  - name: remove lxde-common
    apt:
      name: lxde-common
      state: absent

  # Did not exist in Lubuntu 20.04.
  - name: create /usr/share/lubuntu/images/ if it does not exist
    file:
      path: /usr/share/lubuntu/image
      state: directory
      mode: '0755'
