---

  # if we install anything more powerful get rid of abiword/gnumeric
  - name: remove default office suite
    apt:
      name: "{{item}}"
      state: absent
      purge: yes
    with_items:
      - abiword
      - gnumeric
    when: libreoffice == true or openoffice == true or wpsoffice == true

  - name: install libreoffice
    apt:
      name: "{{item}}"
      state: present
      install_recommends: yes
    with_items:
      - libreoffice-writer
      - libreoffice-calc
      - libreoffice-gtk
      - libreoffice-help-en-us
    when: libreoffice == true
    tags:
      - libreoffice

  # since it's installed by default it matters if we said no to it. It will also conflict with openoffice
  - name: uninstall libreoffice
    apt:
      name: libreoffice*
      state: absent
      purge: yes
    when: libreoffice == false

