---

  #- name: Add canonical third-party mirror
    #apt_repository:
      #repo: "deb {{deb_mirror}}/canonical {{ansible_distribution_release}} partner"
      #state: present
    #tags:
      #- deb_repo

  - name: install additional software
    apt:
      state: latest
      install_recommends: no
      name:
      - audacious
      - audacity
      - cups-client
      - curl
      - gimp
      - imagemagick-6.q16hdri
      - pavucontrol-qt
      - ubuntu-restricted-addons
      - ubuntu-restricted-extras
      - vlc

  # removing bunch of sw I don't need
  - name: remove other apps
    apt:
      state: absent
      purge: yes
      name:
      - cups-browsed
      - deja-dup
      - eog
      - galculator
      - gdb
      - gnome-keyring
      - gnome-logs
      - nautilus
      - sylpheed*
      - update-manager
      - update-notifier
      #- lubuntu-software-center    # Does not exist.
      - update-notifier-common     # Will be installed by "ubuntu-restricted-extras".

   # Purging failed at preseed time since it's removing a file /.../whoopsie-id is that'll be created until the 1st run.
  - name: purge whoopsie
    apt:
      state: absent
      purge: yes
      name:
      - whoopsie
    ignore_errors: true

  - include: sw-office.yml
    tags:
      - office

  - include: sw-browser.yml
    tags:
      - browser

  - name: upgrade Zoom client
    apt:
      deb: "{{ansible_assets_url}}/zoom_amd64.deb"
      only_upgrade: true
    register: zoom_upgraded
    tags:
      - zoom

  - name: install Zoom client for the 1st time
    apt:
      deb: "{{ansible_assets_url}}/zoom_amd64.deb"
    when: zoom_upgraded == 0
    tags:
      - zoom
