---

  - name: set default openldap admin password
    debconf:
      name: slapd
      question: "{{item}}"
      value: "{{ldap_admin_password}}"
      vtype: password
    with_items:
      - slapd/password1
      - slapd/password2
    tags:
      set_password

  - name: install slapd, ldap-utils and tls-related pkgs
    apt:
      name: "{{item}}"
      state: present
    with_items:
      - slapd
      - ldap-utils
      - gnutls-bin
      - ssl-cert

  - name: copy LDIF files
    copy:
      src: "{{item}}"
      # Dest folder will be created if it does not exist.
      dest: /etc/ldap/ldifs/
      mode: 0644
      owner: root
      group: root
      force: yes
    with_items:
      - cttb-init.ldif
      - certinfo.ldif
      - forcetls.ldif

  - name: set up CTTB LDAP initial content
    command: ldapadd -x -D cn=admin,dc=cttb -w "{{ldap_admin_password}}" -f /etc/ldap/ldifs/cttb-init.ldif

  - name: load certificates into LDAP
    command: "{{item}}"
    with_items:
      #- chmod go+rx /etc/ssl/private
      # - chmod go+r /etc/ssl/certs/cttb-cacert.pem /etc/ssl/certs/cttb-ldap-srv_slapd_cert.pem /etc/ssl/private/ldap-srv_slapd_key.pem
        - ldapmodify -Y EXTERNAL -H ldapi:/// -f /etc/ldap/ldifs/certinfo.ldif
        - adduser openldap ssl-cert
        - chgrp ssl-cert /etc/ssl/private/
        - chmod 710 /etc/ssl/private/
        # - chgrp ssl-cert /etc/ssl/private/cakey.pem /etc/ssl/private/ldap-srv_slapd_key.pem
        #- chmod g+r,o-r /etc/ssl/private/cakey.pem /etc/ssl/private/ldap-srv_slapd_key.pem

  - name: require TLS
    command: ldapmodify -Q -Y EXTERNAL -H ldapi:/// -f /etc/ldap/ldifs/forcetls.ldif
