---

  - name: set default openldap admin password
    debconf:
      name: slapd
      question: "{{item}}"
      value: "{{ldap_admin_password}}"
      vtype: password
    with_items:
      - slapd/password1
      - slapd/password2
    tags:
      set_password

  - name: install slapd, ldap-utils and tls-related pkgs
    apt:
      name: "{{item}}"
      state: present
    with_items:
      - slapd
      - ldap-utils
      - gnutls-bin
      - ssl-cert

  - name: set up cttb-ca.info
    copy:
      src: cttb-ca.info
      dest: /etc/ssl/
      owner: root
      group: root
      mode: 0644

  - name: set up cttb-ldap-srv.info
    template:
        src:   cttb-ldap-srv.info.j2
        dest:  /etc/ssl/cttb-ldap-srv.info
        owner: root
        group: root
        mode: 0644

  - name: download CTTB CA certificate
    get_url:
      url: "{{ansible_assets_url}}/cttb-cacert.pem"
      dest: /etc/ssl/certs/cttb-cacert.pem
      mode: 0444

  - name: generate server private key
    command: certtool --generate-privkey --bits 1024 --outfile /etc/ssl/private/ldap-srv_slapd_key.pem
    args:
        creates: /etc/ssl/private/ldap-srv_slapd_key.pem

  - name: generate self-signed server certificate
    command: certtool --generate-certificate --load-privkey /etc/ssl/private/ldap-srv_slapd_key.pem --load-ca-certificate /etc/ssl/certs/cttb-cacert.pem --load-ca-privkey /etc/ssl/private/cakey.pem --template /etc/ssl/cttb-ldap-srv.info --outfile /etc/ssl/certs/cttb-ldap-srv_slapd_cert.pem

  - name: copy LDIF files
    copy:
      src: "{{item}}"
      # Dest folder will be created if it does not exist.
      dest: /etc/ldap/ldifs/
      mode: 0644
      owner: root
      group: root
      force: yes
    with_items:
      - cttb-init.ldif
      - certinfo.ldif
      - forcetls.ldif

  - name: set up CTTB LDAP initial content
    command: ldapadd -x -D cn=admin,dc=cttb -w "{{ldap_admin_password}}" -f /etc/ldap/ldifs/cttb-init.ldif

  - name: load certificates into LDAP
    command: "{{item}}"
    with_items:
        - chmod go+rx /etc/ssl/private
        - chmod go+r /etc/ssl/certs/cttb-cacert.pem /etc/ssl/certs/cttb-ldap-srv_slapd_cert.pem /etc/ssl/private/ldap-srv_slapd_key.pem
        - ldapmodify -Y EXTERNAL -H ldapi:/// -f /etc/ldap/ldifs/certinfo.ldif
        - adduser openldap ssl-cert
        - chgrp ssl-cert /etc/ssl/private/
        - chmod 710 /etc/ssl/private/
        - chgrp ssl-cert /etc/ssl/private/cakey.pem /etc/ssl/private/ldap-srv_slapd_key.pem
        - chmod g+r,o-r /etc/ssl/private/cakey.pem /etc/ssl/private/ldap-srv_slapd_key.pem

  - name: require TLS
    command: ldapmodify -Q -Y EXTERNAL -H ldapi:/// -f /etc/ldap/ldifs/forcetls.ldif
