---

  - name: copy CTTB Root CA certificate
    copy:
      src: CTTB-Root-CA.crt
      dest: /usr/local/share/ca-certificates/CTTB-Root-CA.crt
      owner: root
      group: root
      mode: 0644
      force: yes

  - name: update the system-wide certificate info
    # The "-f" means "fresh". It removes all existing symlinks then regenerate them, thus can delete links for removed authorities.
    command: update-ca-certificates -f

  - name: create cttb-cacert.pem symlink
    file:
      src: /etc/ssl/certs/CTTB-Root-CA.pem
      dest: /etc/ssl/certs/cttb-cacert.pem
      owner: root
      group: root
      state: link

  - name: change the libnssckbi.so files to symlinks if not already
    # If the file is not a symbolic link, back up its content. For all, forcefully change it to a link to the p11-kit-trust.so file.
    shell: locate -b '\libnssckbi.so' | xargs -I{} sh -c 'if [ ! -L {} ]; then cp -p {} {}.orig ; fi ; ln -f -s /usr/lib/x86_64-linux-gnu/pkcs11/p11-kit-trust.so {}'
    tags:
      - gen_symlinks
