---
- block: #set up more bleeding edge mirror, otherwise stable comes from xenial backports
  - name: add lxd ppa key
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: 7635B973
      state: present

  - name: add lxd repo mirror
    apt_repository:
      repo: "deb http://ppa.launchpad.net/ubuntu-lxc/lxd-stable/ubuntu xenial main contrib"
      state: present
  when: "{{lxd_ppa}}"
  tags:
    - lxd_ppa

- name: install lxd pkgs
  apt:
    name: "{{item}}"
    state: latest
    default_release: xenial-backports
    install_recommends: no
  with_items:
    - lxd-client
    - lxd
    - lxd-tools

- name: install support packages
  apt:
    name: "{{item}}"
    state: latest
    install_recommends: no
  with_items:
    - bindfs # for mounting guest fs on host

- name: create zfs pool for containers
  command: lxc storage create {{lxc_storage.name}} {{lxc_storage.type}} source={{lxc_storage.source}}
  when: lxc_storage is defined

- name: add zfs pool to default profile
  command: lxc profile device add default root disk path=/ pool={{lxc_storage.name}}
  when: lxc_storage is defined

#import linux images. Until I setup a https server with special urls I need to do this in two steps
# I use aliases to manage which img is current/latest
- block:
  - name: download the lxc image to tmp files
    get_url:
      url: "{{item.source}}"
      dest: /tmp/lxc-{{item.alias}}.tar.gz
      mode: 0400
    with_items: "{{lxc_images}}"

  - name: import lxc images from files
    command: lxc image import /tmp/lxc-{{item.alias}}.tar.gz --alias {{item.alias}}
    with_items: "{{lxc_images}}"

    # TODO this code to manage tags is bad, really need a module for it, but nothing out there, too complex for a playbook
  - name: remove current 'latest' image alias
    command: lxc image alias delete cttb-latest
    ignore_errors: yes

  - name: set latest image alias
    command: "lxc image alias create cttb-latest {{item.fingerprint}}"
    with_items: '{{lxc_images|selectattr("latest", "defined")|list}}'

  - name: delete image tmp files
    file:
      path: /tmp/lxc-{{item.alias}}.tar.gz
      state: absent
    with_items: "{{lxc_images}}"

  when: lxc_images is defined
  tags:
    - lxc_images

- name: create containers
  become: false
  lxd_container:
    name: "{{item.name}}"
    state: "{{item.state|default('started')}}"
    source:
      type: image
      alias: "{{item.image}}" #implies local repo
    profiles: ["default"]
    devices: "{{item.devices|default(omit)}}"
    config: "{{item.config|default(omit)}}"
    ephemeral: false
    wait_for_ipv4_addresses: true
    timeout: 600
  with_items: "{{lxc_containers|default([])}}"
  tags:
    lxc_containers
