---

nut_mode: standalone

nut_server_address: 127.0.0.1

# This is only an example: you must set this to match your hardware.
nut_ups:
  - name: eaton5s
    # Specify a driver that supports your UPS. See
    # http://networkupstools.org/stable-hcl.html
    driver: usbhid-ups
    port: auto
    description: "Eaton 5S 1500VA (900W)"
    address: 127.0.0.1
    users:
      - name: upsmon
        pass: m0nn34ur
        role: master
        monitor: true
