; CTTB Phone System
; Admin: spike@drba.org

; ####### Extensions allocation #######
; AO & OFFICES  1xxx
; MONKS         2xxx
; NUNS          3xxx
; DRBU          4xxx
; IGVDS         5xxx (000-499 DVBS 500-999 DVGS)
; MISC		6xxx (69xx SERVICES)

[general]
transport=udp
context=from-external
alwaysauthreject=yes
qualify=yes
qualifyfreq=30
rtpkeepalive=30
mwi_from=asterisk

; not needed
;nat=yes
;localnet=10.11.6.1/255.255.224.0
;externaddr=173.166.230.154

[people](!)
type=friend
host=dynamic
disallow=all
allow=ulaw
deny=0.0.0.0/0.0.0.0
; change back after testing, need to restrict to .6.x
;permit=10.11.6.0/255.255.255.0
permit=10.11.6.0/255.255.224.0

#include sip.d/*
