---

  - name: hp gather facts
    ntc_show_command:
      connection: ssh
      platform: hp_procurve
      command: show system
      host: 10.11.12.221
      username: manager
      password: test
      template_dir: /home/administrator/Documents/ansible/new/library/ntc/ntc-templates/templates
    register: result

  - debug: var=result

