---

  - name: install fcitx m17n support for Sanskrit input
    apt:
      name: "{{item}}"
      state: present
    with_items:
      - fcitx-m17n
      - fonts-deva
      - firefox-locale-hi
      - hunspell-hi
      - hyphen-hi
      - libreoffice-l10n-hi
      - libreoffice-help-hi
      - language-pack-hi
      - language-pack-hi-base
      - language-pack-gnome-hi
      - language-pack-gnome-hi-base
    when: sanskrit is defined
    tags:
      - sanskrit

  #- name: configure fcitx-m17n to enable support for deprecated input methods
  #- name: configure fcitx profile to enable sanskrit input method
