---

  - block:
    - name: download Microsoft signing key
      get_url:
        url: https://packages.microsoft.com/keys/microsoft.asc
        dest: /usr/share/keyrings/microsoft.asc
        mode: '0644'

    - name: add VSCode repository
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft.asc] https://packages.microsoft.com/repos/code stable main"
        state: present
        filename: vscode

    - name: install Visual Studio Code
      apt:
        name: code
        state: present
        update_cache: yes

    when: vscode == true
    tags:
      - packages
      - vscode
