# Link-balancer helps maintaining multiple uplinks and
# the relative routing tables

gateway com7 dev com7 gw 172.30.7.1 src 172.30.7.2 check ping 75.75.75.75
gateway com20 dev com20 gw 172.30.20.1 src 172.30.20.2 check ping 75.75.76.76

table com7
    default via com7

table com20
    default via com20

table main
    default via com7 weight 1
    default via com20 weight 1

policy
    connmark 0x7 table com7
    connmark 0x20 table com20
    rules src gw-src-ips com7 table com7
    rules src gw-src-ips com20 table com20
