# Link-balancer helps maintaining multiple uplinks and
# the relative routing tables

gateway com7 dev com7 gw 10.11.7.1 src 10.11.7.111 check ping 8.8.8.8
gateway com20 dev com20 gw 10.11.20.1 src 10.11.20.111 check ping 8.8.4.4

table com7
    default via com7

table com20
    default via com20

table main
    default via com7 weight 1
    default via com20 weight 1

policy
    rules src gw-src-ips com7 table com7
    rules src gw-src-ips com20 table com20
