---

## README
# For this to work there must be an 'interfaces' variable defined. This is normally dons in host_vars
# since this variable is host specific. There are no default in the role for the same reason.
# Var looks something like this:

  # server_interfaces: [
  #  {name: lan, mac: '78:ac:c0:b2:89:b0', auto: True, inet: dhcp},
  #  {name: tr01, mac: '00:60:6e:42:2a:3e', auto: True, inet: dhcp},
  #  {name: tr02, mac: '00:60:6e:42:35:b2', auto: True, inet: dhcp}, ]

# Note that the variable is a list of dict. this is necessary to preserve
# orders as dicts are unordered in python
# If you set inet to static you can provide an ip/netmask/gateway keys to set those up
# A loopback interface is always defined



  - name: assign static interface names
    template:
      src: my-net-names.rules.j2
      dest: /etc/udev/rules.d/70-my-net-names.rules
      owner: root
      group: adm
      mode: 0640
    notify:
      - restart network

  - name: generate new interfaces file
    template:
      src: interfaces.j2
      dest: /etc/network/interfaces
      owner: root
      group: adm
      mode: 0640
    notify:
      - restart network

  - name: setup rt_tables
    lineinfile:
      dest: /etc/iproute2/rt_tables
      regexp: "^{{item.id}} "
      line: "{{item.id}}      {{item.tname}}"
    with_items: "{{server_rt_tables}}"
    when: server_rt_tables is defined


