---
## README
# For this to work there must be an 'interfaces' variable defined.

  - name: assign static interface names
    template:
      src: my-net-names.rules.j2
      dest: /etc/udev/rules.d/70-my-net-names.rules
      owner: root
      group: adm
      mode: 0640
    notify:
      - restart network

  - name: generate new interfaces file
    template:
      src: interfaces.j2
      dest: /etc/network/interfaces
      owner: root
      group: adm
      mode: 0640
    register: gen_net_interfaces

  - name: RESTART THE NETWORK/BOX YOURSELF
    debug:
      msg: interfaces file has been regenerated but networking has not been restarted. Do that yourself as needed.
    when: gen_net_interfaces.changed

  - name: setup rt_tables
    lineinfile:
      dest: /etc/iproute2/rt_tables
      regexp: "^{{item.id}} "
      line: "{{item.id}}      {{item.tname}}"
    with_items: "{{server_rt_tables | default([]) }}"
