---

  - name: configure dns resolution
    template:
      src: resolv.j2
      dest: /etc/resolv.conf
      mode: 0644
      owner: root
      group: root

  - name: configure default grub #servers should give output on boot for debugging
    copy:
      src: default-grub
      dest: /etc/default/grub
      mode: 0644
      owner: root
      group: root
    when: ansible_virtualization_type != "lxc"
    tags:
      - grub
    notify:
      - update grub

  # make sure grub is updated no matter what happens next (ie run update-grub from the handler)
  - meta: flush_handlers 

  - name: remove some basic packages
    apt:
      name: "{{item}}"
      state: absent
      purge: yes
    with_items:
      - resolvconf
      - open-iscsi
      - lxc1
      - lxd-client
      - libiscsi2

  - name: install common server packages
    apt:
      name: "{{item}}"
      state: latest
    with_items:
      - lsscsi

  #TODO this should be implemented in the virt role, maybe split host and guest
  - name: install server packages for qemu guests
    apt:
      name: "{{item}}"
      state: latest
    with_items:
      - acpid
    when: ansible_virtualization_type == "kvm" and ansible_virtualization_role == "guest"

  - include: interfaces.yml
    when: server_interfaces is defined
    tags:
      - network
