---

- hosts: dvgs-dorm koha-kiosk2
  tasks:
    - name: apt update, update chrome, autoremove
      shell: ( /usr/bin/apt-get update && /usr/bin/apt-get install -y google-chrome-stable && /usr/bin/apt-get autoremove -y )
