---

- hosts: dvgs-cs-lab
  tasks:
    - name: apt update
      apt:
        update_cache: yes
      become: yes
    - name: update aptitude
      apt:
        name: chrome
        state: present
      become: yes
    - name: apt update, update chrome, autoremove
      shell: ( /usr/bin/apt-get update && /usr/bin/apt-get install -y google-chrome-stable && /usr/bin/apt-get autoremove -y )
