#!/bin/bash

export ANSIBLE_BASE=${HOME}/Documents/ansible/new
export ANSIBLE_HOSTS="${ANSIBLE_BASE}/hosts"
export ANSIBLE_ROLES="${ANSIBLE_BASE}/roles"
export ANSIBLE_PLAYBOOKS="${ANSIBLE_BASE}/plays"
export ANSIBLE_LOG="${ANSIBLE_BASE}/log/run-`date +"%y%m%d%H%M%S"`.log"
export ANSIBLE_TMP="${ANSIBLE_BASE}/tmp"
