---

  - name: custom apt sources.list
    template:
      src: sources.list.j2
      dest: /etc/apt/sources.list
      mode: 0644
      owner: root
      group: root
    tags:
      - apt

  - name: remove apt source files pointing to old theoverseer repo
    shell: /bin/rm -rf /etc/apt/sources.list.d/theoverseer_*
    tags:
      - remove_old_repo_files
      - apt

  - name: add cttb custom ubuntu repo key
    apt_key:
      url: "{{cttb_repo}}/cttb-repo.gpg.key"
      state: present
    tags:
      - apt

  - name: add cttb custom ubuntu repo
    apt_repository:
      repo: "deb {{cttb_repo}}/apt/ubuntu {{ansible_distribution_release}} main"
      state: present
    tags:
      - apt

  - name: add additional apt repo
    apt_repository:
      repo: "{{item}}"
      state: present
    with_items: "{{additional_apt_repo}}"
    when: additional_apt_repo is defined
    tags:
      - apt
      - additional_apt_repo

  - name: refresh the mirrors
    apt:
      update_cache: yes
    ignore_errors: True
    tags:
      - apt
      - apt_autoremove

  # aptitude is not shipped with 16.04 but ansible needs it to do the upgrade
  - name: install aptitude
    apt:
      name: aptitude
      state: present
    tags:
      - apt

  # in case for whatever reason this is missing, it's useful to add ppas to test stuff
  - name: install apt-add-repository
    apt:
      name: software-properties-common
      state: present
    tags:
      - apt

  # setup durign preseed stage, but just in case, make sure it's there
  - name: Set up ansible/cttb-os authorized_key
    authorized_key:
      user: administrator
      key: "{{item}}"
    with_file:
      - ssh_keys/ansible.pub

  # fix persistent udev rules
  - name: remove net udev rule
    file:
      src: /dev/null
      dest: /etc/udev/rules.d/70-persistent-net.rules
      state: link
      force: yes
    when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty'

  - name: set an explicit proxy if needed
    lineinfile:
      dest: /etc/environment
      line: "{{item}}"
    with_items: "{{global_proxy}}"
    when: global_proxy is defined
    tags:
      - common_proxy

  - name: sync time
    include_role:
      name: time-server

  - name: install CTTB CA cert
    include_role:
      name: cttb-ca-client

  # set hostname
  # don't do this on lxc containers
  # https://github.com/ansible/ansible/issues/19814
  - name: set hostname
    hostname:
      name: "{{inventory_hostname}}"
    when: ansible_virtualization_type != "lxc" and ansible_virtualization_role != "guest"

  - name: fix /etc/hosts
    replace:
      dest: /etc/hosts
      regexp: "computer"
      replace: "{{inventory_hostname}}"
      backup: no

  - name: make ssh use ipv4 only # we disable ipv6 and X11forwarding fails
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: '^AddressFamily inet'
      # Insert the line after "ListenAddress" or "#ListenAddress" lines.
      insertafter: '^.?ListenAddress'
      line: 'AddressFamily inet'
    tags:
      disable_ipv6
    notify:
      - reload ssh
    ignore_errors: yes

  - name: enable centralized logging
    copy:
      src: conf/10-centralized-logging.conf
      dest: /etc/rsyslog.d/10-centralized-logging.conf
      mode: 0644
      owner: root
      group: root
    when: centralized_logging == true
    notify:
      - restart rsyslog
    tags:
      - logging

  - name: add ansible repo key
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: 7BB9C367
      state: present
    tags:
      - apt

  - name: add ansible repo mirror
    apt_repository:
      repo: "deb {{deb_mirror}}/ansible xenial main"
      state: present
    tags:
      - apt

  # sometimes bootstrapped version is not enough to run the rest of the playbook
  - name: upgrade ansible to latest
    apt:
      name: ansible
      state: latest
    tags:
      - apt

  - name: remove some software
    apt:
      name: "{{item}}"
      state: absent
    with_items:
      - popularity-contest
      - nano
      - avahi-daemon
      - pidgin-data
      - pidgin
      - snapd
      - snap-confine
      - transmission-common
      - transmission-gtk
      - transmission
      - ubuntu-core-launcher
    tags:
      - remove_sw

  - name: remove sw requested for this box
    apt:
      name: "{{item}}"
      state: absent
    with_items: "{{remove_sw}}"
    when: remove_sw is defined
    tags:
      - remove_sw

  # exfat-fuse and exfat-utils are for support of exfat file system, FAT with total fs size > 4 GB.
  - name: install basic software
    apt:
      name: "{{item}}"
      state: latest
      install_recommends: yes
    with_items:
      - byobu
      - curl
      - dconf-tools
      - ethtool
      - exfat-fuse
      - exfat-utils
      - fio
      - git
      - hddtemp
      - htop
      - iftop
      - iotop
      - iperf
      - iptraf
      - mtr
      - nload
      - obnam
      - p11-kit-modules
      - quota
      - smartmontools
      - socat
      - tcpdump
      - traceroute
      - udisks2
      - unattended-upgrades
      - util-linux
      - vim
      - wakeonlan
      - whois
    tags:
      - basic_software

  - name: install sw requested for this box
    apt:
      name: "{{item}}"
      state: latest
    with_items: "{{additional_sw | default([])}}"
    tags:
      - additional_sw

  - name: enable unattended upgrades
    copy:
      src: conf/unattended-upgrades
      dest: /etc/apt/apt.conf.d/20auto-upgrades
      mode: 0644
      owner: root
      group: root

  - name: disable ipv6 #defaults to yes
    copy:
      src: conf/disable-ipv6.conf
      dest: /etc/sysctl.d/60-disable-ipv6.conf
      mode: 0644
      owner: root
      group: root
    when: disable_ipv6
    tags:
      - disable_ipv6

  - name: vim saner defaults
    copy:
      src: conf/vimrc
      dest: /etc/skel/.vimrc
      mode: 0644
      owner: root
      group: root

  # administrator account has already been created so the above won't take effect
  - name: vim saner defaults for administrator
    copy:
      src: conf/vimrc
      dest: /home/administrator/.vimrc
      mode: 0644
      owner: administrator
      group: administrator

  - name: dist-upgrade + autoremove purge
    apt:
      autoremove: yes
      purge: yes
      upgrade: dist
    tags:
      - apt

  - name: apt autoremove before a fix is in
    command: /usr/bin/apt-get autoremove -y
    tags:
      - apt
      - apt_autoremove

    # Defined in group_vars, default is en_US.UTF-8.
  - name: set the system locale
    command: /usr/sbin/update-locale LANG={{ locale }} LANGUAGE
    tags:
      - locale
