# This enables centralized logging to log-srv.
# The 10 priority is needed so that this happens before anything else,
# especially 50 which is installed by default from ubuntu and 30 which is used
# by unbound that then stops the logs to avoid double writes

*.*                             @log-srv:514
