[General]
AllowGrabBaseKeypad=true
AllowGrabBaseSpecial=false
AllowGrabLocks=false
AllowGrabMiscKeypad=true
AllowGrabMiscSpecial=true
MultipleActionsBehaviour=last
WindowSize=@Size(750 400)

[Alt%2BPrint.19]
Comment=Take screenshot of a window or region
Enabled=true
Exec=/usr/bin/scrot, -s

[Control%2BAlt%2BL.2]
Comment=Leave
Enabled=true
Exec=/usr/bin/lxqt-leave

[Control%2BAlt%2BT.3]
Comment=Start lxterminal
Enabled=true
Exec=/usr/bin/lxterminal

[Meta%2B0.5]
Comment=Activate task 10
Enabled=true
path=/panel/taskbar/task_10

[Meta%2B1.6]
Comment=Activate task 1
Enabled=true
path=/panel/taskbar/task_1

[Meta%2B2.7]
Comment=Activate task 2
Enabled=true
path=/panel/taskbar/task_2

[Meta%2B3.8]
Comment=Activate task 3
Enabled=true
path=/panel/taskbar/task_3

[Meta%2B4.9]
Comment=Activate task 4
Enabled=true
path=/panel/taskbar/task_4

[Meta%2B5.10]
Comment=Activate task 5
Enabled=true
path=/panel/taskbar/task_5

[Meta%2B6.11]
Comment=Activate task 6
Enabled=true
path=/panel/taskbar/task_6

[Meta%2B7.12]
Comment=Activate task 7
Enabled=true
path=/panel/taskbar/task_7

[Meta%2B8.13]
Comment=Activate task 8
Enabled=true
path=/panel/taskbar/task_8

[Meta%2B9.14]
Comment=Activate task 9
Enabled=true
path=/panel/taskbar/task_9

[Meta%2BR.1]
Comment=Show/hide runner dialog
Enabled=true
path=/runner/show_hide_dialog

[Print.18]
Comment=Take a full-screen screenshot
Enabled=true
Exec=/usr/bin/scrot

[Super_L.4]
Comment=Show/hide main menu
Enabled=true
path=/panel/mainmenu/show_hide

[XF86AudioLowerVolume.15]
Comment=Decrease sound volume
Enabled=true
path=/panel/volume/down

[XF86AudioMute.16]
Comment=Mute/unmute sound volume
Enabled=true
path=/panel/volume/mute

[XF86AudioRaiseVolume.17]
Comment=Increase sound volume
Enabled=true
path=/panel/volume/up
