[dvgs](!)
context=from-internal-dvgs

[5500](people,dvgs)
mailbox=5500@people
secret=R5AG9HYH1J
description=Main Office DVGS HS

[5501](people,dvgs)
mailbox=5501@people
secret=9ZW80XNEMD
description=Teacher's Office DVGS HS

[5502](people,dvgs)
mailbox=5502@people
secret=ET0P3MQZ4X
description=Library DVGS HS

[5503](people,dvgs)
secret=QN852WT9MA
description=DVGS ES Room 103

[5504](people,dvgs)
secret=BXYMMFMJF9
description=DVGS ES Room 104

[5505](people,dvgs)
secret=SJLMTHZUK6
description=DVGS ES Room 111

[5506](people,dvgs)
secret=YVQNWI40U2
description=DVGS ES Room 106

[5507](people,dvgs)
secret=D6CNC9XEUW
description=DVGS ES School Office

[5508](people,dvgs)
secret=5JMX1R4ZBL
description=DVGS ES Room 217

[5509](people,dvgs)
secret=0Q9HVBCO0A
description=DVGS ES Room 221

[5510](people,dvgs)
secret=WSROA9NHXJ
description=DVGS ES Room 203

[5511](people,dvgs)
secret=60PGN4K3ZJ
description=DVGS ES Room 102

[5512](people,dvgs)
secret=33HTHXAXBD
description=DVGS ES Room 220

[5513](people,dvgs)
secret=MAYWINDX57
description=DVGS ES Room 206

[5514](people,dvgs)
secret=NDYEKFNNTR
description=DVGS ES Room 120

[5515](people,dvgs)
secret=HIHITATABYEBYE
description=IITBT DVGS classroom

[5516](people,dvgs)
secret=R5KZL7HUWT
description=IITBT DVGS movement room
