[misc](!)
context=from-internal-misc

; CTTB residents
[6917](people,misc)
callerid=Liu Family <6917>
mailbox=6917@people
secret=waireiami
description=Liu Fam Unicorn

[6990](people,misc)
callerid=Budge Test <6990>
mailbox=6990@test
secret=testingy0!
description=Budge test phone 1

[6991](people,misc)
callerid=Budge Test <6991>
mailbox=6991@test
secret=testingy01!
description=Budge test phone 2

; service numbers are in the 6900-6999 range
[6999](people,misc)
callerid=Spike CTTB Test <6999>
mailbox=6999@test
secret=meh0meh1
description=Spike test phone
