; CTTB Phone System
; Admin: spike@drba.org

; ####### Extensions allocation #######
; AO & OFFICES  1xxx
; MONKS         2xxx
; NUNS          3xxx
; DRBU          4xxx
; IGVDS         5xxx (000-499 DVBS 500-999 DVGS)
; MISC          6xxx (69xx SERVICES)

#include extensions.d/*

[from-external]
include => from-external-vitelity
