; Find-Me / Follow-Me Configuration File
[general]
;
featuredigittimeout=>5000
; The number of ms to wait for a digit input for the callee on whether to take the call or
; not before we consider them "done" entering digits.
;
takecall=>1
; The global default keypress for the callee to take taking the current call. This can be
; a single digit or multiple digits. Default is "1".
; Note this string must not be a substring of declinecall.
;
declinecall=>2
; The global default keypress for the callee to decline taking the current call. This can
; be a single digit or multiple digits. Default is "2".
; Note this string must not be a substring of takecall.
;
call_from_prompt=>followme/call-from
; The global default for the 'Incoming call from' message.
;
norecording_prompt=>followme/no-recording
; The global default for the 'You have an incoming call' message when the caller elects
; not to leave their name or the option isn't set for them to do so.
;
options_prompt=>followme/options
; The global default for the 'Press 1 to accept this call or press 2 to decline it' message.
;
pls_hold_prompt=>followme/pls-hold-while-try
; The global default for 'Please hold while we try and connect your call' message.
;
status_prompt=>followme/status
; The global default for 'The party you're calling isn't at their desk' message.
;
sorry_prompt=>followme/sorry
; The global default for 'I'm sorry, but we were unable to locate your party' message.
;

[4999]
music => default
context => from-internal-drbu
number => 4157277453

; Doug
[4201]
music => default
context => from-internal-drbu
number => 5109141428

; Toni Minor
[4235]
music => default
context => from-internal-drbu
number => 7074626516

; Wayne
[4361]
music => default
context => from-internal-drbu
number => 7072345897

; Angela Justice
; Thursday morning through monday morning
;[4581]
;music => default
;context => from-internal-drbu
;number => 5107767146
