[aooffices](!)
context=from-internal-aooffices

[1000](people,aooffices)
mailbox=1000@people
callerid=CTTB AO <1000>
secret=HAOHITHERE
description=AO front desk phone

[1005](people,aooffices)
mailbox=1005@people
secret=A8XBL6ZNYU
description=AO Server Room

[1010](people,aooffices)
secret=G2XM58JKUM
description=Mountain Gate

[1020](people,aooffices)
mailbox=1020@people
secret=42Q2H2H9H5
description=DM Gong 1234

[1021](people,aooffices)
mailbox=1021@people
secret=53Q3H3H0H6
description=Rui Liu 1234

[1022](people,aooffices)
mailbox=1022@people
secret=64Q4H4H1H7
description=Wei Liu Office DVBS
