[drbu](!)
context=from-internal-drbu

[4998](people,drbu)
mailbox=4998@people
callerid=Spike Iphone <4998>
secret=ohboy!
description=Spike iphone softphone test

[4999](people,drbu)
callerid=Spike DRBU test <4999>
mailbox=4999@people
secret=meh0meh1
description=Spike drbu test phone

[4100](people,drbu)
mailbox=4100@people
secret=EF2U4BNQL6
description=DM Kai DRBU Corner Office Entrance

[4101](people,drbu)
mailbox=4101@people
secret=5QLMCQWVAA
description=Sue DRBU Corner Office

[4201](people,drbu)
mailbox=4201@people
secret=QFE4RTHWJG
description=Doug DRBU RM2

[4501](people,drbu)
mailbox=4501@people
secret=ADAS67987S
description=Marty DRBU RM2

[4301](people,drbu)
mailbox=4301@people
secret=JG8WFQVEHL
description=DM Liang DRBU RM9

[4200](people,drbu)
mailbox=4200@people
secret=4O09RVMNVE
description=Janice DRBU RM27

[4312](people,drbu)
mailbox=4312@people
secret=NMRERWTP0I
description=Jason DRBU RM25

[4215](people,drbu)
mailbox=4215@people
secret=O5TXLD89U5
description=Barbara DRBU RM13

[4220](people,drbu)
mailbox=4220@people
secret=3WB11MJ5AP
description=Shari DRBU RM12

[4222](people,drbu)
mailbox=4222@people
secret=KUOT4E8UPD
description=Ernest DRBU RM30

[4223](people,drbu)
mailbox=4223@people
secret=RQ9LE3RXEF
description=Franklyn DRBU RM26

[4361](people,drbu)
mailbox=4361@people
secret=ZXDCPOI2FD
description=Wayne DRBU RM26

[4311](people,drbu)
mailbox=4311@people
secret=ZB50XI45L4
description=James DRBU RM22

[4233](people,drbu)
mailbox=4233@people
secret=7YM2RMQ3GI
description=Yi-Huan DRBU RM16

[4234](people,drbu)
mailbox=4234@people
secret=S6NGDS784Z
description=Huali DRBU RM16

[4363](people,drbu)
mailbox=4363@people
secret=AQOP422Z12
description=Meilin DRBU RM16

;[4280](people,drbu)
;mailbox=4280@people
;secret=OWGOJOE7MJ
;description=DRBU IWR

[4302](people,drbu)
mailbox=4302@people
secret=924GMTI0RH
description=Angela Morelli DRBU RM34

[4318](people,drbu)
mailbox=4318@people
secret=QOE2N39VXC
description=Thao DRBU RM34

[4281](people,drbu)
mailbox=4281@people
secret=O6GDRZ448I
description=Akpinar DRBU RM3

[4282](people,drbu)
mailbox=4282@people
secret=D398P45ZW5
description=Kien DRBU RM33

[4530](people,drbu)
mailbox=4530@people
secret=RVRJO3BAOD
description=DM Tyan DRBU RM7

[4531](people,drbu)
mailbox=4530@people
secret=RVRJO3BAOE
description=DRBU RM7 Guests

[4315](people,drbu)
mailbox=4315@people
secret=TLKVDCN6NQ
description=Donna DRBU HB C112

[4319](people,drbu)
mailbox=4319@people
secret=RMTWCPFKQ3
description=DM Chuan DRBU RM31

[4581](people,drbu)
mailbox=4581@people
secret=YVHLHHCOG5
description=Angela Justice DRBU RM29

[4216](people,drbu)
mailbox=4216@people
secret=RG7P9HA2OF
description=DM Yi DRBU RM15

[4224](people,drbu)
mailbox=4224@people
secret=3IYC27P3EA
description=DM Chih DRBU RM11

[4218](people,drbu)
mailbox=4218@people
secret=WOHABV24OQ
description=Lauren DRBU RM17

[4219](people,drbu)
mailbox=4219@people
secret=40J3DTBO51
description=Stacy DRBU RM19

[4221](people,drbu)
mailbox=4221@people
secret=E5WFGQE2WN
description=Jessica DRBU RM18

[4211](people,drbu)
mailbox=4211@people
secret=WWOK5K14YI
description=DM Sure DRBU RM4

[4261](people,drbu)
mailbox=4261@people
secret=S5N1D0G6O7
description=DM Deng DRBU Library 1

[4262](people,drbu)
mailbox=4262@people
secret=BM19AX57G2
description=Jia-Hui Hung DRBU Library 2

[4240](people,drbu)
mailbox=4240@people
secret=2DYJWN20I8
description=Writing Lab DRBU RM28

[4263](people,drbu)
mailbox=4263@people
secret=A8B0Z32G45
description=DM Ben DRBU Library 3

[4264](people,drbu)
mailbox=4262@people
secret=RAPB0T1G0D
description=DRBU Reading Room

[4511](people,drbu)
mailbox=4511@people
secret=H4DSB5IUYU
description=Heng Jiao DRBU ToB Finance 1

[4512](people,drbu)
mailbox=4512@people
secret=9ZNBSZBMKY
description=Jin Lian DRBU ToB Finance 2

[4513](people,drbu)
mailbox=4513@people
secret=IE14JWI0IO
description=Jin Yun DRBU ToB Finance 3

[4514](people,drbu)
mailbox=4514@people
secret=YGK4MS4U2V
description=Leonie Tan DRBU ToB Finance 4 
