[dvbs](!)
context=from-internal-dvbs

[5000](people,dvbs)
mailbox=5000@people
secret=A1KXM0WWZW
description=Main Office DVBS

[5006](people,dvbs)
mailbox=5006@people
secret=THQLZHB1S5
description=Translation Room 1234

[5009](people,dvbs)
mailbox=5009@people
secret=KH0LDG7925
description=Calligraphy Room 1234

[5001](people,dvbs)
mailbox=5001@people
secret=38VCT1BA21
description=Room 8 1234 (8th Grade)

[5003](people,dvbs)
mailbox=5003@people
secret=M1AMUTES5Q
description=Room 7 1234 (7th Grade)

[5002](people,dvbs)
mailbox=5002@people
secret=59D2RH5HVZ
description=Room 5 Upstairs DVBS

[5007](people,dvbs)
mailbox=5007@people
secret=5N8D9HX4YK
description=Computer Lab Upstairs DVBS

[5004](people,dvbs)
mailbox=5004@people
secret=618T3GWR5J
description=Room 3 Upstairs DVBS (Mini Room)

[5008](people,dvbs)
mailbox=5008@people
secret=LHGREOFNVP
description=Library Upstairs DVBS

[5005](people,dvbs)
mailbox=5005@people
secret=VWHQYKACDB
description=Music Room

[5012](people,dvbs)
mailbox=5012@people
secret=L2MEE2PFE9
description=Art Room

[5013](people,dvbs)
mailbox=5013@people
secret=F17Y6ZMW14
description=Physics Lab

[5014](people,dvbs)
mailbox=5014@people
secret=972RH224MR
description=Environmental Lab

[5010](people,dvbs)
mailbox=5010@people
secret=RSG9SGRXNY
description=Biology/Chemistry Lab
