[vitel-inbound]
type=friend
dtmfmode=auto
host=inbound33.vitelity.net
context=from-external-vitelity
allow=all
insecure=port,invite
canreinvite=no
			
[vitel-outbound]
type=friend
dtmfmode=auto
host=64.2.142.93
context=from-internal-drbu
allow=all
canreinvite=no
