---

  - name: install squid pkgs
    apt:
      name: squid
      state: latest
      install_recommends: yes
      update_cache: yes

  - name: apt autoremove before a fix is in
    command: /usr/bin/apt-get autoremove -y
    tags:
      - apt_autoremove

  - name: deploy squid.conf
    template:
      src: squid.j2
      dest: /etc/squid/squid.conf
      owner: root
      group: root
      mode: 0640
    notify:
      - restart squid
