---

  # xenial has 2.0 and for link balancing we need at least 3.x
  # I've backported it from yakkety and it's on our new custom repo

  - name: install firewall pkgs
    apt:
      name: "{{item}}"
      state: latest
      install_recommends: yes
      update_cache: yes
      #     allow_unauthenticated: yes
    with_items:
      - firehol
      - firehol-tools
      - fireqos
      - ulogd2 # useful to get fw logs and stats

  - name: setup /etc/default/firehol
    copy:
      src: etc-default-firehol
      dest: /etc/default/firehol
      mode: 0640
      owner: root
      group: root

  - name: setup /etc/firehol/firehol.conf
    template:
      src: firehol.j2
      dest: /etc/firehol/firehol.conf
      mode: 0640
      owner: root
      group: root

  - name: setup ulog2 logrotate
    copy:
      src: logrotate-ulog2
      dest: /etc/logrotate.d/ulogd2
      mode: 0644
      owner: root
      group: root

  - name: setup /etc/firehol/link-balancer.conf
    copy:
      src: link-balancer.conf
      dest: /etc/firehol/link-balancer.conf
      mode: 0640
      owner: root
      group: root

  - name: run link-balancer from cron
    cron:
      name: link-balancer
      minute: "*/1"
      job: /usr/sbin/link-balancer > /dev/null 2>&1

  - name: remember to restart the firewall manually!
    debug:
      msg: We don't restart the fw automatically, do it manually with firehol try

  - include: timelimits.yml
    tags:
      - timelimits
