---

  # xenial has 2.0 and for link balancing we need at least 3.x
  # I've backported it from yakkety and it's on our new custom repo

  - name: add cttb internal repo
    apt_repository:
      repo: 'deb http://theoverseer.cttb/cttb-repo ./'
      state: present
      filename: 'cttb-repo'

  - name: install firewall pkgs
    apt:
      name: "{{item}}"
      state: latest
      install_recommends: yes
      update_cache: yes
      allow_unauthenticated: yes
    with_items:
      - firehol
      - firehol-tools
      - fireqos
      - ulogd2 # useful to get fw logs and stats

  - name: setup /etc/default/firehol
    copy:
      src: etc-default-firehol
      dst: /etc/default/firehol
      mode: 0644
      owner: root
      group: root

  - name: setup /etc/firehol/firehol.conf
    copy:
      src: firehol.conf
      dst: /etc/firehol/firehol.conf
      mode: 0644
      owner: root
      group: root
