# This file is part of an effort to implement centralized logging
# At least temporary however we want to retain local logs as well so extra work
# is needed to send it to both places since unbound either sends everything to
# syslog or to a file.
# For more info see: http://theoverseer.cttb/wiki/index.php/UnboundLogConfiguration

# Because order matters in rsyslog and by default ubuntu ships with a
# 50-default.conf that sends everything to syslog, we want this to have this
# defined earlier, hence the 30 numbering.

# unbound writes its log file in the format (from unbound.conf
# man page): [seconds since 1970] unbound[pid:tid]: type: message.
# Examples:
#   [1486533046] unbound[6214:0] info: 10.11.14.1 76.21.11.10.in-addr.arpa. PTR IN
#   [1486533046] unbound[6214:0] info: 10.11.11.239 ssl.gstatic.com. A IN
# So created the format below. The msg part contains:
#   " [6214:0] info: 10.11.11.239 ssl.gstatic.com. A IN"
# Used the substring :2:$ to remove the leading space. The prefix "-"
# before the log file name disables synchronous logging.
# The "stop" directive discards the msg, otherwise the
# "*.*;auth,authpriv.none -/var/log/syslog" line below logs it again.
#
# Ref:
# 1. Forward only when the program name is "unbound":
#    http://askubuntu.com/questions/186592/how-do-i-configure-rsyslog-to-send-logs-from-a-specific-program-to-a-remote-sysl
# 2. Log format properties:
#    http://www.rsyslog.com/doc/v8-stable/configuration/properties.html
# 3. Property replacer: (to change time to epoch time)
#    http://www.rsyslog.com/doc/v8-stable/configuration/property_replacer.html
# 4. Remove leading space in "msg":
#    http://lists.adiscon.net/pipermail/rsyslog/2008-July/024101.html
# 5. Configuring Rsyslog To Stop The Logging Of Certain Messages
#    http://serverfault.com/questions/366023/configuring-rsyslog-to-stop-the-logging-of-certain-messages
#


$template UnboundLogFormat,"[%timegenerated:::date-unixtimestamp%] unbound%msg:2:$%\n"
if $programname == 'unbound' then {
    -/var/log/unbound/unbound.log;UnboundLogFormat
    stop
}

